#!/usr/bin/env python3
"""Gate: MODULE.md public symbols match code for touched Tier 1/2 modules.

Until #1859 this gate passed vacuously for every PR: `parse_architecture_map`
matched no row of `docs/architecture/map.md`, so `touched` below was always
empty and the per-module loop never ran. With the parser fixed, the drift that
had been accumulating unseen since the gate was written becomes visible all at
once. `KNOWN_DRIFT_ALLOWLIST` names that pre-existing drift, per (module, kind)
with every symbol spelled out, so the gate goes from vacuously green to
genuinely green without turning every open PR red on day one. It is temporary
by construction: `tests/harness/test_module_md_sync_parser.py` fails when an
allowlisted symbol stops being real drift, so the list cannot outlive what it
excuses or quietly become the gate's resting state.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "ci"))
from common import (  # noqa: E402
    ChangedFilesUnresolved,
    backend_module_root,
    git_changed_files,
    module_for_file,
    module_public_symbols_from_code,
    parse_architecture_map,
    parse_args,
    parse_module_md_public_symbols,
    print_check_result,
    resolve_issue_number,
)


@dataclass(frozen=True)
class AllowedDrift:
    """Pre-existing drift excused by name, with the reason it is excused."""

    reason: str
    symbols: tuple[str, ...]


ORPHAN_REASON = (
    "Pre-existing orphan drift, measured on 2026-09-14 at the moment #1859 made "
    "this gate honest. Verified causes: an annotated module-level constant "
    "(`NAME: tuple[str, ...] = ...`) is an ast.AnnAssign and invisible to "
    "ast_public_symbols; a symbol re-exported only from `__init__.py` is skipped "
    "because module_public_symbols_from_code ignores `_`-prefixed files; and "
    "MODULE.md prose still backticks names that are not symbols. Burning this "
    "down needs the code-side extractor widened, which moves the counts for "
    "every Tier 1/2 module, so it is a follow-up with its own evidence. Each "
    "symbol here is removable on its own."
)
UNDOCUMENTED_REASON = (
    "Pre-existing undocumented drift, measured on 2026-09-14 at the moment "
    "#1859 made this gate honest. ast_public_symbols admits every module-level "
    "public name in every non-`_` file — including `logger = "
    "logging.getLogger(__name__)` and CLI `main`/`build_parser` entrypoints — "
    "while MODULE.md documents the module's facade. Narrowing the extractor "
    "moves the counts for every Tier 1/2 module at once and is a separate "
    "change with its own blast radius and its own evidence (#1859 scope "
    "decision). Each symbol here is removable on its own."
)


KNOWN_DRIFT_ALLOWLIST: dict[str, dict[str, AllowedDrift]] = {
    "backend/ai/ad_performance": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "AD_ACTIONS",
                "GOLDEN_AD_FIXTURES",
                "HOLD_CONFIDENCE_THRESHOLD",
                "SPARSE_MAX_CONFIDENCE",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AdPerformanceModel",
                "InferenceResult",
                "TrainResult",
                "build_parser",
                "derive_ad_action",
                "is_sparse_ad_history",
                "main",
            ),
        ),
    },
    "backend/ai/anomaly": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ANOMALY_CLASSES",
                "ANOMALY_CONFIDENCE_THRESHOLD",
                "GOLDEN_ANOMALY_FIXTURES",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "InferenceResult",
                "TrainResult",
                "build_parser",
                "main",
            ),
        ),
    },
    "backend/ai/artifacts": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "experimental",
                "promoted",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ArtifactBundle",
                "ArtifactError",
                "ArtifactLoadError",
                "ArtifactPublishError",
                "LoadedModel",
                "feature_columns_for_suite",
            ),
        ),
    },
    "backend/ai/dataset": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ADS_COLUMNS",
                "LABELS_COLUMNS",
                "ORDERS_COLUMNS",
                "ORDER_ITEMS_COLUMNS",
                "RETURNS_COLUMNS",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "RETURN_CONDITION_VALUES",
                "RETURN_STATUS_VALUES",
                "build_parser",
                "generate_ads",
                "generate_order",
                "generate_order_item",
                "generate_return",
                "generate_shop",
                "generate_synthetic_dataset",
                "main",
                "masked_buyer_id",
                "rand_status",
                "rand_timestamp",
                "vnd",
            ),
        ),
    },
    "backend/ai/features": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "AD_FEATURE_COLUMNS",
                "ANOMALY_FEATURE_COLUMNS",
                "SELLER_STAGE_FEATURE_COLUMNS",
                "ad_spend_30d_vnd",
                "feature_columns",
                "frame",
                "gmv_30d_vnd",
                "grain",
                "metadata",
                "order_count_30d",
                "return_rate_30d",
                "shop_age_days",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "assert_anomaly_input_columns",
                "in_last_n_days",
                "load_ads",
                "load_order_items",
                "load_orders",
                "load_returns",
                "parse_timestamp",
                "resolve_dataset_dir",
                "resolve_reference_date",
                "window_start",
            ),
        ),
    },
    "backend/ai/recommendations": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "action_type",
                "composite_score",
                "computed_at",
                "confidence",
                "creator_id",
                "creator_name",
                "cta",
                "match_score",
                "message",
                "predicted_outcome",
                "product_name",
                "score_grade",
                "session_id",
                "sku_id",
                "source",
                "tiktok_product_id",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "LivestreamScriptClassification",
                "LivestreamScriptRecommendation",
                "PriceDirectionSuggestion",
                "ProductRecommendation",
                "acknowledge_livestream_script",
                "build_recommendation_message",
                "classify_livestream_performance",
                "classify_product_trend",
                "get_livestream_script_recommendation",
                "get_price_direction_suggestion",
                "get_trending_product_recommendation",
            ),
        ),
    },
    "backend/ai/seller_stage": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "AD_SPEND_GROWTH_MIN_VND",
                "ORDER_COUNT_GROWTH_MIN",
                "ORDER_COUNT_NEW_MAX",
                "RETURN_RATE_LEAKAGE_MIN",
                "SHOP_AGE_NEW_MAX_DAYS",
                "STAGE_BOUNDARY_FIXTURES",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ComparisonReport",
                "InferenceResult",
                "SellerStageProfile",
                "StageBoundaryFixture",
                "TrainResult",
                "build_parser",
                "main",
            ),
        ),
    },
    "backend/api": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "DemoExecutionRecord",
                "__all__",
                "get_current_user",
                "shop_id",
                "workflow_runs",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ActionCardInputsData",
                "ActionCardInputsResponse",
                "ActionCardItem",
                "ActionCardRefreshData",
                "ActionCardRefreshResponse",
                "ActionCardsListResponse",
                "ConfirmationDecisionRequest",
                "ConfirmationDecisionResponse",
                "ContentSessionResponse",
                "CorrelationIdMiddleware",
                "CreatorContentResponse",
                "CreatorResponse",
                "DemoDecisionApproveData",
                "DemoDecisionApproveResponse",
                "DemoDecisionDetailResponse",
                "DemoDecisionExpectedImpact",
                "DemoDecisionItem",
                "DemoDecisionListResponse",
                "DemoDecisionReasoning",
                "DemoDecisionRecommendation",
                "ExecutionEnqueueData",
                "ExecutionEnqueueRequest",
                "ExecutionEnqueueResponse",
                "ExecutionStatusData",
                "ExecutionStatusResponse",
                "OrderResponse",
                "OutcomeIngestData",
                "OutcomeIngestRequest",
                "OutcomeIngestResponse",
                "PaginatedCreators",
                "PaginatedOrders",
                "PaginatedProducts",
                "PendingDecisionSummary",
                "PredictedOutcomePayload",
                "ProductResponse",
                "RecommendationItem",
                "RecommendationsResponse",
                "ReorderBasis",
                "ShopResponse",
                "TikTokBusinessAccountHolderCallbackResult",
                "TikTokVerifyConnectionResponse",
                "WorkflowOutcomeMetricsResponse",
                "WorkflowRunListItem",
                "WorkflowRunListResponse",
                "app",
                "approve_demo_decision",
                "cancel_run",
                "confirm_shipment",
                "enqueue_execution",
                "get_action_card_inputs",
                "get_business_account_holder_auth",
                "get_business_advertiser_oauth_service",
                "get_creator_content",
                "get_current_shop",
                "get_demo_analytics",
                "get_demo_decision",
                "get_demo_redis_client",
                "get_demo_reference_shop_id",
                "get_execution_status",
                "get_heartbeat_interval_s",
                "get_poll_interval_s",
                "get_run_event_subscriber",
                "get_run_events_session_factory",
                "get_tiktok_oauth_service",
                "get_verify_connection_service",
                "get_workflow_outcome_metrics",
                "handle_tiktok_webhook",
                "health",
                "install_error_boundary",
                "lifespan",
                "list_action_cards",
                "list_creators",
                "list_demo_decisions",
                "list_demo_runs",
                "list_orders",
                "list_products",
                "list_recommendations",
                "list_shops",
                "logger",
                "record_outcome",
                "refresh_action_cards",
                "router",
                "stream_run_events",
                "submit_confirmation_decision",
                "tiktok_business_account_holder_callback",
                "tiktok_business_advertiser_oauth_callback",
                "tiktok_oauth_callback",
                "verify_tiktok_connection",
            ),
        ),
    },
    "backend/core/security": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "SUPABASE_URL",
                "User",
                "__all__",
                "credential_resolver",
                "dependencies",
                "get_or_create",
                "jwt",
                "jwt_expired",
                "jwt_invalid",
                "jwt_jwks_unavailable",
                "kid",
                "sub",
                "users",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "BindingVerifier",
                "JwksClient",
                "REFRESH_BUFFER",
                "RefreshAuth",
                "RefreshOutcome",
                "RefreshStatus",
                "build_refresh_auth_from_env",
                "logger",
                "refresh_credential",
                "resolve_production_read_credential",
                "resolve_sandbox_write_credential",
            ),
        ),
    },
    "backend/database": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ActionCard",
                "ActionCardsRepo",
                "AlertConfig",
                "AlertConfigsRepo",
                "AlertHistory",
                "AlertHistoryRepo",
                "Base",
                "Campaign",
                "Creator",
                "CreatorsRepo",
                "GraphEdge",
                "GraphRepo",
                "InventoryItem",
                "InventoryRepo",
                "Livestream",
                "LivestreamsRepo",
                "Order",
                "OrdersRepo",
                "ProcessedEvent",
                "ProcessedEventsRepo",
                "Product",
                "ProductsRepo",
                "Recommendation",
                "RecommendationsRepo",
                "SET",
                "Settlement",
                "SettlementsRepo",
                "Shop",
                "ShopScopedRepo",
                "ShopsRepo",
                "TikTokCredential",
                "TikTokCredentialRepo",
                "User",
                "UsersRepo",
                "__all__",
                "after_begin",
                "set_config",
                "shop_id",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "clear_tenant_context",
                "create_engine",
                "create_session_factory",
                "decrypt_token",
                "downgrade",
                "encrypt_token",
                "ensure_worker_session_factory",
                "get_tenant_context",
                "get_tenant_scoped_tables",
                "logger",
                "run_migrations_offline",
                "run_migrations_online",
                "set_tenant_context",
                "upgrade",
            ),
        ),
    },
    "backend/integrations/tiktok": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ANALYTICS_BESTSELLING_PRODUCTS_PATH",
                "ANALYTICS_BESTSELLING_VIDEOS_PATH",
                "ANALYTICS_LIVE_OVERVIEW_PERFORMANCE_PATH",
                "ANALYTICS_LIVE_PERFORMANCE_LIST_PATH",
                "ANALYTICS_SHOP_PERFORMANCE_PATH",
                "ANALYTICS_SHOP_PRODUCTS_PERFORMANCE_PATH",
                "ANALYTICS_SHOP_SKUS_PERFORMANCE_PATH",
                "CANCELLATION_SEARCH_PATH",
                "DEFAULT_OPEN_API_BASE_URL",
                "FINANCE_STATEMENTS_PATH",
                "INVENTORY_SEARCH_PATH",
                "MARKETPLACE_CREATORS_SEARCH_PATH",
                "ORDER_SEARCH_PATH",
                "PRODUCT_SEARCH_PATH",
                "RETURN_SEARCH_PATH",
                "__all__",
                "strip_nones",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AuthorizedShop",
                "AuthorizedShopsData",
                "CancellationsSearchData",
                "CreatorContentDetail",
                "CreatorContentSearchData",
                "FinanceStatement",
                "FinanceStatementsData",
                "GuardedTikTokClient",
                "MarketplaceCreator",
                "MarketplaceCreatorsSearchData",
                "MerchantCapability",
                "OrdersSearchData",
                "PaginatedData",
                "ProductsSearchData",
                "ReactiveRefreshNeedsReauthError",
                "ReadOnlyTransportGuard",
                "ReturnsSearchData",
                "SandboxOnlyWriteGuard",
                "T",
                "TikTokCancellation",
                "TikTokModel",
                "TikTokOrder",
                "TikTokProduct",
                "TikTokReturnOrder",
                "TransportGuard",
                "call_with_reactive_refresh",
                "category_attributes_path",
                "coerce_model",
                "derive_return_condition",
                "derive_return_type",
                "fulfillment_batch_ship_path",
                "fulfillment_combine_packages_path",
                "fulfillment_ship_package_path",
                "fulfillment_split_order_path",
                "fulfillment_uncombine_package_path",
                "is_production_read_allowed",
                "is_sandbox_write_allowed",
                "log_outbound_request",
                "logger",
                "marketplace_creator_path",
                "normalize_path",
                "path_contains_write_marker",
                "product_detail_path",
                "product_edit_path",
                "product_inventory_update_path",
                "product_prices_update_path",
                "promotion_activity_products_path",
                "promotion_deactivate_path",
                "supply_chain_confirm_shipment_path",
                "transient_partner_error",
                "uses_header_auth",
                "validate_data",
                "validate_items",
            ),
        ),
    },
    "backend/services/action_cards": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ACTION_CARD_REFRESH_COOLDOWN_SECONDS",
                "ActionCard",
                "DAILY_SCORING_CRON_UTC",
                "DecisionEmissionConfig",
                "DecisionEmissionNoveltyLedger",
                "IN_FLIGHT_STATUSES",
                "REDIS_URL",
                "RuntimeError",
                "SUPPRESSED_REASONS",
                "SUPPRESSED_REASON_WEEKLY_NOVELTY_CAP",
                "_COOLDOWN",
                "_WEEKLY_NOVELTY_CAP",
                "_dismiss_cooldown_expired",
                "action_cards",
                "active_cap",
                "approved",
                "bind_celery_dispatchers",
                "commit",
                "computed_at",
                "cooldown",
                "cooldown_days",
                "dismissed",
                "emission_budget_applied",
                "executing",
                "ix_action_cards_shop_surfaced_at",
                "max_active",
                "recommendations",
                "redis",
                "refresh_cooldown",
                "run_daily_scoring_for_shop",
                "socket_connect_timeout",
                "socket_timeout",
                "status",
                "suppressed_reason",
                "suppressed_weekly_novelty_cap",
                "surfaced_at",
                "test_approved_and_executing_are_never_time_boxed_superseded",
                "test_inflight_status_not_overwritten_by_rescoring",
                "test_suppressed_candidate_is_still_recomputed_on_next_scoring_run",
                "test_weekly_novelty_cap_reason_is_structurally_unreachable",
                "test_worked_example_six_novel_candidates_default_config_fills_zero_idle_slots",
                "try_acquire",
                "updated_at",
                "weekly_novelty_cap",
                "workflow_key",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CooldownDecision",
                "get_refresh_dispatcher",
                "logger",
                "set_refresh_cooldown_gate",
                "set_refresh_dispatcher",
            ),
        ),
    },
    "backend/services/agent": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "BANNED_PATTERNS_JSON_PATH",
                "ExecutionErrorCategory",
                "PER_RESULT_TOKEN_CEILING",
                "PER_RESULT_TOKEN_TARGET",
                "RETRYABLE_VENDOR_CODES",
                "cap",
                "category",
                "count",
                "height",
                "juli",
                "omitted_count",
                "result",
                "retryable",
                "seller",
                "text",
                "truncated",
                "value",
                "width",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AbuseLimitDecision",
                "AbuseLimitGate",
                "ActionCardNotActive",
                "ActionCardNotFound",
                "ApprovalResult",
                "AssistantTextEvent",
                "AssistantTextPayload",
                "AssistantTurn",
                "BannedPatternEntry",
                "BannedPatternHit",
                "CHECK_PRODUCT_STATUS_SPEC",
                "CONCLUDE_WITHOUT_CHANGES_SPEC",
                "CappedImages",
                "CappedList",
                "CappedText",
                "CheckProductStatusInput",
                "CheckProductStatusOutput",
                "ComposeIntegrityError",
                "ConcludeWithoutChangesInput",
                "ConcludeWithoutChangesOutput",
                "ConcurrencyConflict",
                "ConcurrencyExhaustedError",
                "ConcurrencyGuard",
                "ConcurrencyMatch",
                "ConfirmationOptionPayload",
                "ConversationStore",
                "DuplicateToolError",
                "EventPublisher",
                "EventSink",
                "FakeLLMService",
                "FinalResponse",
                "GET_PRODUCT_INFORMATION_SPEC",
                "GET_SEO_KEYWORDS_SPEC",
                "GetProductInformationInput",
                "GetProductInformationOutput",
                "GetSeoKeywordsInput",
                "GetSeoKeywordsOutput",
                "GoldenScenario",
                "INSPECT_PRODUCT_IMAGE_SPEC",
                "ImageDimensions",
                "ImageInspector",
                "InMemoryAbuseLimitGate",
                "InMemoryEventSink",
                "InspectProductImageEdit",
                "InspectProductImageFinding",
                "InspectProductImageInput",
                "InspectProductImageOutput",
                "InspectionConfig",
                "IterationGate",
                "IterationGateAction",
                "JsonbConversationStore",
                "JuliText",
                "LLMConfig",
                "LLMConfigOverride",
                "LLMProviderError",
                "LLMService",
                "LedgerStatus",
                "ModelPrice",
                "Money",
                "MutableProductFields",
                "NoPendingConfirmationError",
                "NoProductsForShop",
                "OPTIMIZE_PRODUCT_PLAYBOOK",
                "OPTIMIZE_PRODUCT_TERMINATION_POLICY",
                "OpenAIResponsesAdapter",
                "PendingConfirmationWrite",
                "PersistingEventSink",
                "Playbook",
                "PlaybookStep",
                "PlaybookToolResolutionError",
                "ProductSkuPrice",
                "ProductToolContext",
                "ProductToolExecutor",
                "RecordedCall",
                "RedisAbuseLimitGate",
                "RollupValues",
                "RunResult",
                "RunState",
                "RunStateFieldMissingError",
                "ScenarioStaleness",
                "ScriptExhaustedError",
                "SellerFacingCompletionReason",
                "SellerFacingDeclinedReason",
                "SellerFacingRefusalReason",
                "SellerText",
                "StopReason",
                "TerminationPolicy",
                "TextBlock",
                "ToolCallBlock",
                "ToolClassification",
                "ToolCompletedEvent",
                "ToolCompletedPayload",
                "ToolDefinition",
                "ToolExecutionError",
                "ToolExecutionLedger",
                "ToolExecutionRequestPayload",
                "ToolExecutionUnrecoverableError",
                "ToolExecutor",
                "ToolPolicy",
                "ToolRegistry",
                "ToolSpec",
                "ToolStartedEvent",
                "ToolStartedPayload",
                "TranslatedError",
                "UPDATE_PRODUCT_LISTING_SPEC",
                "UPDATE_PRODUCT_PRICE_SPEC",
                "UPLOAD_PRODUCT_IMAGE_SPEC",
                "UnavailableAbuseLimitGate",
                "UnknownConcurrencyScopedOperationError",
                "UnknownToolError",
                "UnknownWorkflowKeyError",
                "UnreleasedPromptVersionError",
                "UnresolvedAgentRefError",
                "UnresolvedSkuRefError",
                "UnresolvedStagedImageError",
                "UpdateProductListingInput",
                "UpdateProductListingOutput",
                "UpdateProductPriceInput",
                "UpdateProductPriceOutput",
                "UploadProductImageInput",
                "UploadProductImageOutput",
                "Usage",
                "VendorText",
                "VerifyOutcome",
                "VerifyReadBack",
                "WorkflowApprovalRequiredEvent",
                "WorkflowApprovalRequiredPayload",
                "WorkflowCompletedEvent",
                "WorkflowCompletedPayload",
                "WorkflowFailedEvent",
                "WorkflowFailedPayload",
                "WorkflowNotExecutable",
                "WorkflowRunStatus",
                "WorkflowRunner",
                "WorkflowStartedEvent",
                "WorkflowStartedPayload",
                "WorkflowStatusEvent",
                "WorkflowStatusPayload",
                "accumulate_running_seconds",
                "append_continuation",
                "approve_action_card",
                "approve_rate_limit_burst_max_requests",
                "approve_rate_limit_burst_window_seconds",
                "approve_rate_limit_max_requests",
                "approve_rate_limit_window_seconds",
                "bind_agent_abuse_limit_gate",
                "build_confirmation_options",
                "build_image_inspector",
                "build_llm_service",
                "build_opening_context_message",
                "build_product_tool_registry",
                "build_read_resources",
                "build_write_resources",
                "canonicalize_params",
                "capture_basis_snapshot",
                "capture_run_as_scenario",
                "check_scenarios",
                "classify_crash_stop_reason",
                "compile_python_patterns",
                "completed_required_steps",
                "compose",
                "compute_params_sha",
                "confirmation_rate_limit_max_requests",
                "confirmation_rate_limit_window_seconds",
                "effective_iteration_cap",
                "estimate_cost_usd",
                "evaluate_checkpoint",
                "evaluate_iteration_gate",
                "extension_grant_narration",
                "extension_grant_phase_narration",
                "extract_mutable_fields",
                "field_scope_for",
                "from_source",
                "get_agent_abuse_limit_gate",
                "handle_check_product_status",
                "handle_conclude_without_changes",
                "handle_get_product_information",
                "handle_get_seo_keywords",
                "handle_inspect_product_image",
                "handle_update_product_listing",
                "handle_update_product_price",
                "handle_upload_product_image",
                "initial_run_state",
                "iso_utc_timestamp",
                "load_scenario",
                "log_abuse_limit_exceeded",
                "logger",
                "main",
                "measurable_write_tool_names",
                "normalize_inspection",
                "numeric_value",
                "production_version",
                "prompt_sha256",
                "prompt_version",
                "publish_event_best_effort",
                "register_product_read_tools",
                "register_product_write_tools",
                "register_terminal_tools",
                "required_steps_completed",
                "resolve_llm_config",
                "run_events_channel",
                "running_seconds_column_value",
                "seed_replay_run",
                "set_agent_abuse_limit_gate",
                "sse_max_concurrent_streams",
                "sse_retry_after_seconds",
                "status_for",
                "to_json_safe",
                "validate_playbook_tools",
            ),
        ),
    },
    "backend/services/aggregates": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "AnalyticsPerformanceInterval",
                "AnalyticsPerformanceRepo",
                "InventoryRepo",
                "MID_LARGE_SHOP",
                "NEW_SHOP",
                "ORDER_DISPATCH_SLA_HOURS",
                "OrderItemsRepo",
                "OrdersRepo",
                "ProductsRepo",
                "ReturnsRepo",
                "Shop",
                "TikTokSyncStateRepo",
                "conversion_rate",
                "null",
                "shop_profile",
                "unavailable",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AnalyticsKpiRollup",
                "HealthDataSource",
                "HealthSnapshot",
                "ProxyHealthSignals",
                "ShopProfile",
                "ShopProfileSignals",
                "compute_after_sales_handling_time_hours",
                "compute_analytics_weighted_product_ctr",
                "compute_conversion_rate_by_category",
                "compute_csat_proxy",
                "compute_dsi_days",
                "compute_fulfillment_accuracy_rate",
                "compute_inventory_turnover",
                "compute_orders_at_sla_risk",
                "compute_promotion_efficiency_denominators",
                "compute_repeat_purchase_rate",
                "compute_seller_fault_cancellation_rate",
                "compute_shop_traffic_conversion_rate",
                "compute_stockout_rate",
            ),
        ),
    },
    "backend/services/alerts": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=("alert_type",),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "build_alert_copy",
                "cooldown_seconds",
                "logger",
                "parse_threshold",
                "rule_matches",
            ),
        ),
    },
    "backend/services/analytics_backfill": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ANALYTICS_BACKFILL_CONCURRENCY_LIMIT",
                "AnalyticsBackfillPartitionsRepo",
                "AsyncSession",
                "RateLimiter",
                "active_products",
                "attempts",
                "budget_lock",
                "catalog",
                "catalog_point_in_time",
                "complete",
                "concurrency_limit",
                "coverage_pct",
                "failed",
                "failures",
                "finish",
                "mark_complete",
                "new_products",
                "product",
                "rate_limited",
                "record_attempt",
                "record_failure",
                "record_rate_limited",
                "search_all",
                "session_lock",
                "should_stop",
                "skipped",
                "stopped_reason",
                "successes",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ACTIVE_PRODUCT_STATUSES",
                "ALLOWED_BUCKETS",
                "AnalyticsResourceProtocol",
                "BACKFILL_WINDOW_START",
                "BucketCoverageResult",
                "CatalogCountStrategy",
                "CatalogCounts",
                "CatalogPartitionResult",
                "FORBIDDEN_BUCKETS",
                "LiveAnalyticsResource",
                "LivePartitionResult",
                "OrchestratorResult",
                "ProductPartitionResult",
                "ProductPerformanceResource",
                "ProductsSearch",
                "assert_no_forbidden_live_backfill_paths",
                "backfill_live_allowed_get_paths",
                "backfill_main",
                "build_coverage_parser",
                "build_live_shop_rollup_kwargs",
                "build_parser",
                "compute_catalog_counts",
                "compute_live_hours",
                "compute_live_sessions_count",
                "coverage_main",
                "coverage_ratio",
                "coverage_report_to_dict",
                "derive_aov",
                "is_retryable_partition_error",
                "iter_calendar_days",
                "logger",
                "main",
                "persist_partition_failure",
                "sum_live_impressions",
                "sum_live_views",
            ),
        ),
    },
    "backend/services/etl": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "DLQ_CHANNEL",
                "KafkaRecord",
                "RAW_CHANNELS",
                "__all__",
                "channel",
                "dlq",
                "duplicate",
                "make_etl_handoff",
                "processed",
                "received_at",
                "shop_key",
                "value",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ProcessedEvent",
                "ProcessedEventsRepo",
                "SilverAnalyticsPromoter",
                "SilverOrdersReturnsPromoter",
                "append_targeted_ctor_payload",
                "append_targeted_live_hours_payload",
                "bronze_order_to_upsert_kwargs",
                "bronze_return_to_upsert_kwargs",
                "extract_event_id",
                "logger",
            ),
        ),
    },
    "backend/services/execution": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "error",
                "error_category",
                "idempotency_key",
                "tool_name",
                "workflow_key",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ExecutionErrorCategory",
                "ExecutionStatus",
                "PreconditionFailure",
                "PreconditionName",
                "TaskDispatcher",
                "ToolRouteEntry",
                "WorkflowOutcomeRecorder",
                "classify_execution_error",
                "clear_excess_inventory_handler",
                "create_activity_handler",
                "create_hero_product_handler",
                "create_queued_execution",
                "delete_activity_handler",
                "get_rls_boot_check_state",
                "is_tool_registered",
                "logger",
                "mark_execution_finished",
                "optimize_product_handler",
                "record_rls_boot_check_passed",
                "register_async_tool",
                "replenish_inventory_handler",
                "resolve_write_capability",
                "run_approved_tool",
                "run_clear_excess_inventory_chain",
                "run_create_activity_chain",
                "run_create_hero_product_chain",
                "run_delete_activity_chain",
                "run_optimize_product_chain",
                "run_replenish_inventory_chain",
                "run_tool_async",
                "run_update_activity_chain",
                "screen_and_reencode_image",
                "screen_upload_file",
                "update_activity_handler",
            ),
        ),
    },
    "backend/services/feedback": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=("idempotency_key",),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "OutcomeIngestResult",
                "logger",
            ),
        ),
    },
    "backend/services/ingestion": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "DlqHandoffFn",
                "EtlConsumer",
                "HandoffFn",
                "create_app",
            ),
        ),
    },
    "backend/services/operations": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "APPROVED_STATUSES",
                "CARDS_SURFACED",
                "COUNTABLE_CONFIDENCES",
                "DISMISSED_STATUSES",
                "EXCLUDED_CONFIDENCES",
                "EXPIRY_STOP_REASON",
                "KIND_PRECEDENCE",
                "PENDING_STATUSES",
                "RECOMMENDATIONS_WITH_AN_OBSERVED_OUTCOME",
                "RUNS_STARTED",
                "ratio",
                "stop_reason",
                "workflow_outcome_metrics",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ActionExecution",
                "ActionLink",
                "ApprovalRate",
                "CountableReading",
                "ExcludedReading",
                "ExecutionQuality",
                "IncrementalImpactLink",
                "ObservedMetric",
                "ObservedOutcomeLink",
                "ProductionWriteAuthorizationService",
                "RecommendationLink",
                "RecommendationQuality",
                "RunNotFoundError",
                "StateChangeLink",
                "StateChangeRecord",
                "VALIDATED_WORKFLOW_IDS",
                "WorkflowOutcomeRecordResult",
                "build_parser",
                "extract_workflow_id",
                "is_validated_workflow_id",
                "issue_authorization",
                "logger",
                "main",
                "revoke_authorization",
            ),
        ),
    },
    "backend/services/scoring": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "DAILY_SCORING_CRON_UTC",
                "DAILY_SCORING_UTC_HOUR",
                "WORKFLOW_COPY_TEMPLATE_KEYS",
                "build_feature_aggregates",
                "clear_excess_4",
                "copy_source",
                "create_activity_7a",
                "create_hero_product_1",
                "delete_activity_7b",
                "expected_impact",
                "health_check_results",
                "next_steps",
                "one_line",
                "optimize_product_2",
                "prevent_cancellation_8a",
                "prevent_refund_8c",
                "prevent_return_8b",
                "process_order_5",
                "replenish_inventory_3",
                "rules_proxy",
                "source_kpi_ids",
                "unavailable",
                "update_activity_7c",
                "why",
                "workflow_key",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "VisualLayerDomain",
                "WorkflowExpectedImpact",
                "WorkflowReasoningSummary",
                "WorkflowRecommendation",
                "get_workflows_for_profile",
            ),
        ),
    },
    "backend/services/tiktok": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ACCOUNT_LIFECYCLE_CHANNEL",
                "EVENT_CATEGORY_ROUTES",
                "PHASE2_CATALOG",
                "PHASE2_CATALOG_IDS",
                "__all__",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CatalogEntry",
                "CredentialBindingError",
                "DatabaseRawWebhookEventRecorder",
                "DatabaseWebhookSideEffects",
                "NoopWebhookSideEffects",
                "RawWebhookEventRecorder",
                "TikTokBusinessAdvertiserOAuthCallbackResult",
                "TikTokBusinessAdvertiserOAuthService",
                "TikTokOAuthCallbackParams",
                "TikTokOAuthCallbackResult",
                "TikTokOAuthNotConfiguredError",
                "TikTokOAuthTokenExchangeFailed",
                "TikTokVerifyConnectionService",
                "TikTokWebhookPayload",
                "WebhookProcessResult",
                "WebhookSideEffects",
                "access_token_expires_at",
                "account_holder_merchant_id",
                "app_review_user_id",
                "build_partner_oauth_facade",
                "build_tiktok_oauth_service",
                "catalog_id_for_event",
                "complete_tiktok_oauth_callback",
                "ingest_channel_for_event",
                "is_deferred_webhook_type",
                "is_material_catalog_id",
                "logger",
                "make_binding_verifier",
                "persist_account_holder_tokens",
                "persist_advertiser_oauth_tokens",
                "persist_oauth_tokens",
                "redact_webhook_body",
                "resolve_authorized_shop",
                "tiktok_debug_enabled",
                "verify_capability_binding",
            ),
        ),
    },
    "backend/services/webhook": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "DatabaseRawWebhookEventRecorder",
                "EVENT_CATEGORY_ROUTES",
                "HandoffFn",
                "RawWebhookEventRecorder",
                "WEBHOOK_PATH",
                "__all__",
                "raw_event_recorder",
                "session_factory",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CeleryMaterialAnalyticsDispatcher",
                "InMemoryMaterialEnqueueGate",
                "MaterialAnalyticsDispatcher",
                "MaterialEnqueueGate",
                "RedisMaterialEnqueueGate",
                "app",
                "get_material_analytics_dispatcher",
                "get_material_enqueue_gate",
                "health",
                "lifespan",
                "logger",
                "make_material_etl_handoff",
                "material_compute_env_ready",
                "maybe_enqueue_material_analytics_compute",
                "run_material_analytics_compute",
                "set_material_analytics_dispatcher",
                "set_material_enqueue_gate",
            ),
        ),
    },
    "backend/workers/services/polling": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "HandoffFn",
                "PermissionDeniedError",
                "ProductionReadClientFactory",
                "RateLimiter",
                "TikTokAPIError",
                "TikTokOAuthService",
                "TikTokSyncStateRepo",
                "end_date_lt",
                "inventory_last_sync_at",
                "make_etl_handoff",
                "production_read",
                "rate_limited",
                "refresh_merchant_tokens",
                "resolve_production_read_credential",
                "start_date_ge",
                "sync_livestreams",
                "sync_settlements",
                "sync_state",
                "tiktok_sync_state",
                "time_until_reset",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "check_sandbox_write_catalog_identity_mismatch",
                "logger",
                "mismatch_logger",
                "run_fujiwa_material_resource_fetch",
                "sync_products_with_local_upsert",
                "sync_sandbox_write_products",
            ),
        ),
    },
}


def module_symbols(module_path: str) -> tuple[set[str], set[str]]:
    """(documented, actual) public symbols for a module path from the map."""
    module_md = backend_module_root(module_path) / "MODULE.md"
    return parse_module_md_public_symbols(module_md), module_public_symbols_from_code(module_path)


def _allowed(module_path: str, kind: str) -> set[str]:
    entry = KNOWN_DRIFT_ALLOWLIST.get(module_path, {}).get(kind)
    return set(entry.symbols) if entry else set()


def run_check(issue: int) -> tuple[bool, str, dict[str, Any]]:  # noqa: ARG001
    modules = parse_architecture_map()
    try:
        changed = git_changed_files()
    except ChangedFilesUnresolved as exc:
        # Never a silent pass: an unresolvable diff is reported with its cause,
        # the same way harness_bootstrap_pin.py degrades (#1540, #1571).
        return (
            False,
            f"Changed-file set unresolved: {exc.reason}",
            {
                "drift": [],
                "missingInterfaces": [],
                "touchedModules": [],
                "allowlisted": [],
                "changedFilesUnresolved": exc.reason,
            },
        )
    touched: set[str] = set()
    for path in changed:
        mod = module_for_file(path, modules)
        if mod:
            touched.add(mod)
    drift: list[dict] = []
    allowlisted: list[str] = []
    for module_path in sorted(touched):
        info = modules.get(module_path)
        if not info or info.tier >= 3:
            continue
        module_md = backend_module_root(module_path) / "MODULE.md"
        if not module_md.exists():
            drift.append({"module": module_path, "error": "MODULE.md missing"})
            continue
        documented, actual = module_symbols(module_path)
        excused_missing = _allowed(module_path, "undocumented")
        excused_orphan = _allowed(module_path, "orphan")
        missing = sorted((actual - documented) - excused_missing)
        orphans = sorted((documented - actual) - excused_orphan)
        allowlisted.extend(
            f"{module_path}:undocumented:{s}"
            for s in sorted((actual - documented) & excused_missing)
        )
        allowlisted.extend(
            f"{module_path}:orphan:{s}" for s in sorted((documented - actual) & excused_orphan)
        )
        if missing or orphans:
            drift.append(
                {
                    "module": module_path,
                    "missingInModuleMd": missing,
                    "orphanInModuleMd": orphans,
                }
            )

    details = {
        "drift": drift,
        "missingInterfaces": [d.get("missingInModuleMd", []) for d in drift],
        "touchedModules": sorted(touched),
        "allowlisted": allowlisted,
    }
    if drift:
        return False, "MODULE.md drift detected", details
    return True, "MODULE.md in sync for touched modules", details


def main() -> int:
    args = parse_args("Validate MODULE.md drift")
    issue = resolve_issue_number(args.issue)
    if issue is None:
        print("error: issue number required", file=sys.stderr)
        return 1
    passed, _, details = run_check(issue)
    detail = ""
    if details.get("changedFilesUnresolved"):
        detail = f"changed-file set unresolved: {details['changedFilesUnresolved']}"
    elif details.get("drift"):
        detail = f"{len(details['drift'])} module(s) out of sync"
    else:
        detail = (
            f"{len(details['touchedModules'])} module(s) checked, "
            f"{len(details['allowlisted'])} allowlisted symbol(s)"
        )
    return print_check_result("module_md_sync", passed, detail)


if __name__ == "__main__":
    raise SystemExit(main())
