#!/usr/bin/env python3
"""Gate: MODULE.md public symbols match code for touched Tier 1/2 modules.

Until #1859 this gate passed vacuously for every PR: `parse_architecture_map`
matched no row of `docs/architecture/map.md`, so `touched` below was always
empty and the per-module loop never ran. With the parser fixed, the drift that
had been accumulating unseen since the gate was written becomes visible all at
once. `KNOWN_DRIFT_ALLOWLIST` names that pre-existing drift, per (module, kind)
with every symbol spelled out, so the gate goes from vacuously green to
genuinely green without turning every open PR red on day one. It is temporary
by construction: `tests/harness/test_module_md_sync_parser.py` fails when an
allowlisted symbol stops being real drift, so the list cannot outlive what it
excuses or quietly become the gate's resting state.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "ci"))
from common import (  # noqa: E402
    ChangedFilesUnresolved,
    backend_module_root,
    git_changed_files,
    module_for_file,
    module_public_symbols_from_code,
    parse_architecture_map,
    parse_args,
    parse_module_md_public_symbols,
    print_check_result,
    resolve_issue_number,
)


@dataclass(frozen=True)
class AllowedDrift:
    """Pre-existing drift excused by name, with the reason it is excused."""

    reason: str
    symbols: tuple[str, ...]


ORPHAN_REASON = (
    "Pre-existing orphan drift, derived on 2026-09-15 after #1859 taught this "
    "gate to read the tree it had been reporting on. 198 entries, against the "
    "322 the same measurement produced before four parser defects were fixed: "
    "an annotated constant was an ast.AnnAssign and invisible to "
    "ast_public_symbols; a bullet's explanation counted as a declaration, so "
    "prose named tables and attributes as symbols; the first correction to "
    "that inverted the label-first convention and hid 96 real exports; and a "
    "`from ... import (...)` fence, the most explicit form of all, was read by "
    "no version of the parser. A deliberate over-read remains on this side: a "
    "label-first bullet's tail is scanned whole, so a symbol another module "
    "owns, named in dependency prose, lands here. That is the safe direction "
    "-- it can only over-report an orphan, never lose a documented symbol. "
    "What is left is a name a MODULE.md documents that the module no longer "
    "exports. Each is removable on its own. Burn-down is tracked in #1963."
)
UNDOCUMENTED_REASON = (
    "Pre-existing undocumented drift, derived on 2026-09-15. 809 entries. It "
    "grew when #1859 taught ast_public_symbols to see annotated and plain "
    "module-level constants, which are real exports no MODULE.md had listed, "
    "and shrank again when the parser learned to read a `from ... import "
    "(...)` fence as a declaration. Excluded as never anyone's interface: "
    "`logger` and `log` (NEVER_AN_EXPORT), and Alembic revision bookkeeping "
    "under migrations/versions. What is left is a public name the module "
    "really exports and its MODULE.md really does not name, in a bullet or in "
    "a fence. backend/services/operations was burned to zero as the worked "
    "example (#1859 AC5) and is absent from this list. Each symbol is "
    "removable on its own, by documenting it. Burn-down is tracked in #1963."
)


KNOWN_DRIFT_ALLOWLIST: dict[str, dict[str, AllowedDrift]] = {
    "backend/ai/ad_performance": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AdAction",
                "AdPerformanceModel",
                "CLASS_IMBALANCE_STRATEGY",
                "CUT_ROAS_RATIO",
                "DEFAULT_RANDOM_SEED",
                "InferenceResult",
                "SCALE_ROAS_RATIO",
                "SPARSE_HISTORY_MIN_CLICKS",
                "SPARSE_HISTORY_MIN_CONVERSIONS",
                "SPARSE_HISTORY_MIN_IMPRESSIONS",
                "TrainResult",
                "build_parser",
                "derive_ad_action",
                "is_sparse_ad_history",
                "main",
            ),
        ),
    },
    "backend/ai/anomaly": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ANOMALY_LABEL_CLASSES",
                "CLASS_IMBALANCE_STRATEGY",
                "DEFAULT_RANDOM_SEED",
                "InferenceResult",
                "TrainResult",
                "build_parser",
                "main",
            ),
        ),
    },
    "backend/ai/artifacts": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "experimental",
                "promoted",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AD_PERFORMANCE_MAX_ROAS_MAPE",
                "ANOMALY_MIN_PRECISION",
                "ANOMALY_MIN_RECALL",
                "ArtifactBundle",
                "ArtifactError",
                "ArtifactLoadError",
                "ArtifactPublishError",
                "LoadedModel",
                "METADATA_FILENAME",
                "METRICS_FILENAME",
                "MODEL_FILENAME",
                "MODEL_SUITES",
                "ModelSuite",
                "PromotionStatus",
                "SELLER_STAGE_MIN_PRECISION",
                "SELLER_STAGE_MIN_RECALL_MACRO",
                "feature_columns_for_suite",
            ),
        ),
    },
    "backend/ai/dataset": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ANOMALY_BASE_RATE",
                "DATASET_VERSION",
                "ITEM_SWAP_RATIO",
                "REPEAT_BUYER_RATE",
                "REQUIRED_PARQUET_FILES",
                "RETURN_CONDITION_VALUES",
                "RETURN_STATUS_VALUES",
                "build_parser",
                "generate_ads",
                "generate_order",
                "generate_order_item",
                "generate_return",
                "generate_shop",
                "generate_synthetic_dataset",
                "main",
                "masked_buyer_id",
                "rand_status",
                "rand_timestamp",
                "vnd",
            ),
        ),
    },
    "backend/ai/features": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "FORBIDDEN_ANOMALY_INPUT_COLUMNS",
                "FORBIDDEN_ANOMALY_INPUT_PREFIXES",
                "assert_anomaly_input_columns",
                "in_last_n_days",
                "load_ads",
                "load_order_items",
                "load_orders",
                "load_returns",
                "parse_timestamp",
                "resolve_dataset_dir",
                "resolve_reference_date",
                "window_start",
            ),
        ),
    },
    "backend/ai/recommendations": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ACTION_ADJUST_COMMISSION",
                "ACTION_CONTACT_CREATOR",
                "ACTION_SCHEDULE_LIVE",
                "Confidence",
                "LivestreamScriptClassification",
                "LivestreamScriptRecommendation",
                "LlmGenerator",
                "PriceDirectionSuggestion",
                "ProductRecommendation",
                "TrendTier",
                "acknowledge_livestream_script",
                "build_recommendation_message",
                "classify_livestream_performance",
                "classify_product_trend",
                "get_livestream_script_recommendation",
                "get_price_direction_suggestion",
                "get_trending_product_recommendation",
            ),
        ),
    },
    "backend/ai/seller_stage": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CLASS_IMBALANCE_STRATEGY",
                "ComparisonReport",
                "DEFAULT_RANDOM_SEED",
                "InferenceResult",
                "SellerStage",
                "SellerStageProfile",
                "StageBoundaryFixture",
                "TrainResult",
                "build_parser",
                "main",
            ),
        ),
    },
    "backend/api": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "DemoExecutionRecord",
                "__all__",
                "get_current_user",
                "shop_id",
                "workflow_runs",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ActionCardInputsData",
                "ActionCardInputsResponse",
                "ActionCardItem",
                "ActionCardRefreshData",
                "ActionCardRefreshResponse",
                "ActionCardsListResponse",
                "ChartRange",
                "ConfirmationDecisionRequest",
                "ConfirmationDecisionResponse",
                "ContentSessionResponse",
                "CorrelationIdMiddleware",
                "CreatorContentResponse",
                "CreatorResponse",
                "DEFAULT_BUSINESS_API_BASE_URL",
                "DEFAULT_PAGE_LIMIT",
                "DemoDecisionApproveData",
                "DemoDecisionApproveResponse",
                "DemoDecisionDetailResponse",
                "DemoDecisionExpectedImpact",
                "DemoDecisionItem",
                "DemoDecisionListResponse",
                "DemoDecisionReasoning",
                "DemoDecisionRecommendation",
                "ExecutionEnqueueData",
                "ExecutionEnqueueRequest",
                "ExecutionEnqueueResponse",
                "ExecutionStatusData",
                "ExecutionStatusResponse",
                "GENERIC_ERROR_DETAIL",
                "OrderResponse",
                "OutcomeIngestData",
                "OutcomeIngestRequest",
                "OutcomeIngestResponse",
                "PaginatedCreators",
                "PaginatedOrders",
                "PaginatedProducts",
                "PendingDecisionSummary",
                "PredictedOutcomePayload",
                "ProductResponse",
                "RecommendationItem",
                "RecommendationsResponse",
                "ReorderBasis",
                "ShopResponse",
                "TikTokBusinessAccountHolderCallbackResult",
                "TikTokVerifyConnectionResponse",
                "WorkflowOutcomeMetricsResponse",
                "WorkflowRunListItem",
                "WorkflowRunListResponse",
                "app",
                "approve_demo_decision",
                "cancel_run",
                "confirm_shipment",
                "enqueue_execution",
                "get_action_card_inputs",
                "get_business_account_holder_auth",
                "get_business_advertiser_oauth_service",
                "get_creator_content",
                "get_current_shop",
                "get_demo_analytics",
                "get_demo_decision",
                "get_demo_redis_client",
                "get_demo_reference_shop_id",
                "get_execution_status",
                "get_heartbeat_interval_s",
                "get_poll_interval_s",
                "get_run_event_subscriber",
                "get_run_events_session_factory",
                "get_tiktok_oauth_service",
                "get_verify_connection_service",
                "get_workflow_outcome_metrics",
                "handle_tiktok_webhook",
                "health",
                "install_error_boundary",
                "lifespan",
                "list_action_cards",
                "list_creators",
                "list_demo_decisions",
                "list_demo_runs",
                "list_orders",
                "list_products",
                "list_recommendations",
                "list_shops",
                "record_outcome",
                "refresh_action_cards",
                "router",
                "stream_run_events",
                "submit_confirmation_decision",
                "tiktok_business_account_holder_callback",
                "tiktok_business_advertiser_oauth_callback",
                "tiktok_oauth_callback",
                "verify_tiktok_connection",
            ),
        ),
    },
    "backend/core/security": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "__all__",
                "credential_resolver",
                "dependencies",
                "jwt",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "BindingVerifier",
                "DEFAULT_JWKS_CACHE_TTL_SECONDS",
                "DEFAULT_MIN_REFETCH_INTERVAL_SECONDS",
                "JwksClient",
                "REFRESH_BUFFER",
                "RefreshAuth",
                "RefreshOutcome",
                "RefreshStatus",
                "build_refresh_auth_from_env",
                "refresh_credential",
                "resolve_production_read_credential",
            ),
        ),
    },
    "backend/database": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ActionCard",
                "ActionCardsRepo",
                "AlertConfig",
                "AlertConfigsRepo",
                "AlertHistory",
                "AlertHistoryRepo",
                "Base",
                "Campaign",
                "Creator",
                "CreatorsRepo",
                "GraphEdge",
                "GraphRepo",
                "InventoryItem",
                "InventoryRepo",
                "Livestream",
                "LivestreamsRepo",
                "Order",
                "OrdersRepo",
                "ProcessedEvent",
                "ProcessedEventsRepo",
                "Product",
                "ProductsRepo",
                "Recommendation",
                "RecommendationsRepo",
                "SET",
                "Settlement",
                "SettlementsRepo",
                "Shop",
                "ShopScopedRepo",
                "ShopsRepo",
                "TikTokCredential",
                "TikTokCredentialRepo",
                "User",
                "UsersRepo",
                "__all__",
                "__getattr__",
                "after_begin",
                "set_config",
                "shop_id",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ENCRYPTED_TOKEN_PREFIX",
                "TABLE_CLASSIFICATION_MAP",
                "VIA_PARENT_MAPPINGS",
                "clear_tenant_context",
                "config",
                "create_engine",
                "create_session_factory",
                "decrypt_token",
                "encrypt_token",
                "ensure_worker_session_factory",
                "get_tenant_context",
                "get_tenant_scoped_tables",
                "run_migrations_offline",
                "run_migrations_online",
                "set_tenant_context",
                "target_metadata",
            ),
        ),
    },
    "backend/integrations/tiktok": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "__all__",
                "capabilities",
                "guarded_client",
                "guards",
                "strip_nones",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ACCESS_TOKEN_PATH",
                "AFFILIATE_CONTENT_API_VERSION",
                "AFFILIATE_SELLER_API_VERSION",
                "ANALYTICS_API_VERSION",
                "ANALYTICS_BESTSELLING_API_VERSION",
                "ANALYTICS_SHOP_PERFORMANCE_PER_HOUR_API_VERSION",
                "ANALYTICS_SHOP_PRODUCTS_LIST_API_VERSION",
                "AUTHORIZATION_API_VERSION",
                "AUTHORIZED_SHOPS_PATH",
                "AuthorizedShop",
                "AuthorizedShopsData",
                "CREATOR_CONTENT_DETAILS_PATH",
                "CancellationsSearchData",
                "CreatorContentDetail",
                "CreatorContentSearchData",
                "DEFAULT_AUTH_BASE_URL",
                "DEFAULT_BASE_URL",
                "DEFAULT_BUSINESS_API_BASE_URL",
                "FINANCE_API_VERSION",
                "FULFILLMENT_API_VERSION",
                "FinanceStatement",
                "FinanceStatementsData",
                "GuardedTikTokClient",
                "MarketplaceCreator",
                "MarketplaceCreatorsSearchData",
                "MerchantCapability",
                "OAUTH_ACCESS_TOKEN_PATH",
                "ORDER_API_VERSION",
                "ORDER_DETAIL_API_VERSION",
                "ORDER_DETAIL_PATH",
                "OrdersSearchData",
                "PARTNER_AUTH_URL",
                "PRODUCTION_READ_GET_EXACT",
                "PRODUCTION_READ_GET_PATTERNS",
                "PRODUCTION_READ_POST_PATHS",
                "PRODUCT_API_VERSION",
                "PRODUCT_BRANDS_PATH",
                "PRODUCT_CATEGORIES_PATH",
                "PRODUCT_CREATE_PATH",
                "PRODUCT_FILE_UPLOAD_PATH",
                "PRODUCT_IMAGE_UPLOAD_PATH",
                "PRODUCT_INVENTORY_API_VERSION",
                "PRODUCT_LISTING_API_VERSION",
                "PRODUCT_PREREQUISITES_PATH",
                "PRODUCT_SEO_API_VERSION",
                "PRODUCT_SEO_WORDS_PATH",
                "PRODUCT_SUGGESTIONS_PATH",
                "PROMOTION_API_VERSION",
                "PROMOTION_CREATE_PATH",
                "PaginatedData",
                "ProductsSearchData",
                "RETURN_REFUND_SEARCH_API_VERSION",
                "ReactiveRefreshNeedsReauthError",
                "ReturnsSearchData",
                "SANDBOX_ALLOWED_REQUESTS",
                "SUPPLY_CHAIN_API_VERSION",
                "SandboxOnlyWriteGuard",
                "T",
                "TikTokCancellation",
                "TikTokModel",
                "TikTokOrder",
                "TikTokProduct",
                "TikTokReturnOrder",
                "TransportGuard",
                "WRITE_PATH_PATTERNS",
                "call_with_reactive_refresh",
                "category_attributes_path",
                "coerce_model",
                "derive_return_condition",
                "derive_return_type",
                "fulfillment_batch_ship_path",
                "fulfillment_combine_packages_path",
                "fulfillment_ship_package_path",
                "fulfillment_split_order_path",
                "fulfillment_uncombine_package_path",
                "is_production_read_allowed",
                "is_sandbox_write_allowed",
                "log_outbound_request",
                "marketplace_creator_path",
                "normalize_path",
                "path_contains_write_marker",
                "product_detail_path",
                "product_edit_path",
                "product_inventory_update_path",
                "product_prices_update_path",
                "promotion_activity_products_path",
                "promotion_deactivate_path",
                "supply_chain_confirm_shipment_path",
                "transient_partner_error",
                "uses_header_auth",
                "validate_data",
                "validate_items",
            ),
        ),
    },
    "backend/services/action_cards": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ActionCard",
                "CDP_DECISION_EMISSION_COOLDOWN_DAYS",
                "CDP_DECISION_EMISSION_MAX_ACTIVE",
                "CDP_DECISION_EMISSION_WEEKLY_NOVELTY_CAP",
                "DAILY_SCORING_CRON_UTC",
                "DecisionEmissionConfig",
                "DecisionEmissionNoveltyLedger",
                "REDIS_URL",
                "RuntimeError",
                "SUPABASE_JWT_SECRET",
                "_COOLDOWN",
                "_WEEKLY_NOVELTY_CAP",
                "_dismiss_cooldown_expired",
                "action_cards",
                "active",
                "active_cap",
                "approved",
                "commit",
                "cooldown",
                "cooldown_days",
                "decision_emission_novelty_ledger",
                "dismissed",
                "dismissed_at",
                "emission_budget_applied",
                "executing",
                "ix_action_cards_shop_surfaced_at",
                "max_active",
                "recommendations",
                "redis",
                "refresh_cooldown",
                "run_daily_scoring_for_shop",
                "socket_connect_timeout",
                "socket_timeout",
                "status",
                "suppressed_weekly_novelty_cap",
                "surfaced_at",
                "test_approved_and_executing_are_never_time_boxed_superseded",
                "test_inflight_status_not_overwritten_by_rescoring",
                "test_suppressed_candidate_is_still_recomputed_on_next_scoring_run",
                "test_weekly_novelty_cap_reason_is_structurally_unreachable",
                "test_worked_example_six_novel_candidates_default_config_fills_zero_idle_slots",
                "try_acquire",
                "updated_at",
                "weekly_novelty_cap",
                "workflow_key",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CooldownDecision",
                "SUPPRESSED_REASON_ACTIVE_CAP",
                "SUPPRESSED_REASON_COOLDOWN",
                "get_refresh_dispatcher",
                "set_refresh_cooldown_gate",
                "set_refresh_dispatcher",
            ),
        ),
    },
    "backend/services/agent": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "abuse_limits",
                "approval",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ABUSE_LIMIT_EXCEEDED_EVENT",
                "AGENT_OUTPUT_SCOPE",
                "AbuseLimitDecision",
                "AbuseLimitGate",
                "AgentReadResources",
                "AssistantTextEvent",
                "AssistantTextPayload",
                "AssistantTurn",
                "AsyncSessionFactory",
                "Block",
                "CHECK_PRODUCT_STATUS_SPEC",
                "CONCLUDE_WITHOUT_CHANGES_SPEC",
                "COPY_LAYER_SCOPE",
                "CheckProductStatusInput",
                "CheckProductStatusOutput",
                "Clock",
                "ComposeIntegrityError",
                "ConcludeWithoutChangesInput",
                "ConcludeWithoutChangesOutput",
                "ConcurrencyCheckResult",
                "ConcurrencyConflict",
                "ConcurrencyExhaustedError",
                "ConcurrencyGuard",
                "ConcurrencyMatch",
                "ConfirmationOptionPayload",
                "ConversationMessage",
                "ConversationStore",
                "DEFAULT_BASE_URL",
                "DEFAULT_MAX_OUTPUT_TOKENS",
                "DEFAULT_MODEL",
                "DEFAULT_REQUEST_TIMEOUT_SECONDS",
                "DEFAULT_SCENARIO_DIR",
                "DEFAULT_TEMPERATURE",
                "DIRECT_RUN_RATIONALE",
                "DuplicateToolError",
                "EVENT_TYPES",
                "EventPublisher",
                "EventSink",
                "FAILURE_STOP_REASONS",
                "FIELD_SCOPE_BY_OPERATION",
                "FakeLLMService",
                "FinalResponse",
                "GET_PRODUCT_INFORMATION_SPEC",
                "GET_SEO_KEYWORDS_SPEC",
                "GetProductInformationInput",
                "GetProductInformationOutput",
                "GetSeoKeywordsInput",
                "GetSeoKeywordsOutput",
                "GoldenScenario",
                "INSPECT_PRODUCT_IMAGE_SPEC",
                "ImageInspector",
                "InMemoryAbuseLimitGate",
                "InMemoryEventSink",
                "InspectProductImageEdit",
                "InspectProductImageFinding",
                "InspectProductImageInput",
                "InspectProductImageOutput",
                "InspectionConfig",
                "IterationGate",
                "IterationGateAction",
                "JULI_SOURCE",
                "JsonbConversationStore",
                "JuliText",
                "LLMConfig",
                "LLMConfigOverride",
                "LLMProviderError",
                "LLMService",
                "LedgerStatus",
                "LedgerWriteOutcomeRecorder",
                "MUTABLE_FIELD_NAMES",
                "Message",
                "ModelPrice",
                "Money",
                "MutableProductFields",
                "NON_TERMINAL_STATUSES",
                "NoPendingConfirmationError",
                "Number",
                "OPERATION_APPROVE",
                "OPERATION_CONFIRMATION",
                "OPERATION_SSE",
                "OPTIMIZE_PRODUCT_PLAYBOOK",
                "OPTIMIZE_PRODUCT_TERMINATION_POLICY",
                "OpenAIResponsesAdapter",
                "PRICE_TABLE_USD_PER_MILLION_TOKENS",
                "PRODUCTION_PROMPT_VERSION",
                "PRODUCT_READ_TOOL_HANDLERS",
                "PRODUCT_WRITE_TOOL_HANDLERS",
                "PROVENANCE_SOURCES",
                "PendingConfirmationWrite",
                "PersistingEventSink",
                "Playbook",
                "PlaybookStep",
                "PlaybookToolResolutionError",
                "ProductSkuPrice",
                "ProductToolContext",
                "ProductToolExecutor",
                "ProvenanceEnvelope",
                "ProvenanceSource",
                "RecordedCall",
                "RedisAbuseLimitGate",
                "RollupValues",
                "RunResult",
                "RunState",
                "RunStateFieldMissingError",
                "SEVERITIES",
                "STOP_REASON_TO_STATUS",
                "ScenarioStaleness",
                "ScriptExhaustedError",
                "SellerFacingCompletionReason",
                "SellerFacingDeclinedReason",
                "SellerFacingRefusalReason",
                "SellerText",
                "StopReason",
                "TERMINAL_TOOL_HANDLERS",
                "TIKTOK_PRODUCT_EDIT_CATEGORY_VERSION",
                "TerminationPolicy",
                "TextBlock",
                "ToolCallBlock",
                "ToolClassification",
                "ToolCompletedEvent",
                "ToolCompletedPayload",
                "ToolDefinition",
                "ToolExecutionError",
                "ToolExecutionLedger",
                "ToolExecutionRequestPayload",
                "ToolExecutionUnrecoverableError",
                "ToolExecutor",
                "ToolPolicy",
                "ToolRegistry",
                "ToolSpec",
                "ToolStartedEvent",
                "ToolStartedPayload",
                "UPDATE_PRODUCT_LISTING_SPEC",
                "UPDATE_PRODUCT_PRICE_SPEC",
                "UPLOAD_PRODUCT_IMAGE_SPEC",
                "UnavailableAbuseLimitGate",
                "UnknownConcurrencyScopedOperationError",
                "UnknownToolError",
                "UnknownWorkflowKeyError",
                "UnreleasedPromptVersionError",
                "UnresolvedAgentRefError",
                "UnresolvedSkuRefError",
                "UnresolvedStagedImageError",
                "UpdateProductListingInput",
                "UpdateProductListingOutput",
                "UpdateProductPriceInput",
                "UpdateProductPriceOutput",
                "UploadProductImageInput",
                "UploadProductImageOutput",
                "Usage",
                "VERDICTS",
                "VendorText",
                "VerifyOutcome",
                "VerifyReadBack",
                "WORKFLOW_KEY",
                "WorkflowApprovalRequiredEvent",
                "WorkflowApprovalRequiredPayload",
                "WorkflowCompletedEvent",
                "WorkflowCompletedPayload",
                "WorkflowFailedEvent",
                "WorkflowFailedPayload",
                "WorkflowRunEvent",
                "WorkflowRunEventAdapter",
                "WorkflowRunStatus",
                "WorkflowRunner",
                "WorkflowStartedEvent",
                "WorkflowStartedPayload",
                "WorkflowStatusEvent",
                "WorkflowStatusPayload",
                "WriteOutcomeRecorder",
                "accumulate_running_seconds",
                "append_continuation",
                "approve_rate_limit_burst_max_requests",
                "approve_rate_limit_burst_window_seconds",
                "approve_rate_limit_max_requests",
                "approve_rate_limit_window_seconds",
                "bind_agent_abuse_limit_gate",
                "build_confirmation_options",
                "build_image_inspector",
                "build_llm_service",
                "build_opening_context_message",
                "build_product_tool_registry",
                "build_read_resources",
                "build_write_resources",
                "canonicalize_params",
                "capture_basis_snapshot",
                "capture_run_as_scenario",
                "check_scenarios",
                "classify_crash_stop_reason",
                "compile_python_patterns",
                "completed_required_steps",
                "compose",
                "compute_params_sha",
                "confirmation_rate_limit_max_requests",
                "confirmation_rate_limit_window_seconds",
                "effective_iteration_cap",
                "estimate_cost_usd",
                "evaluate_checkpoint",
                "evaluate_iteration_gate",
                "extension_grant_narration",
                "extension_grant_phase_narration",
                "extract_mutable_fields",
                "field_scope_for",
                "from_source",
                "get_agent_abuse_limit_gate",
                "handle_check_product_status",
                "handle_conclude_without_changes",
                "handle_get_product_information",
                "handle_get_seo_keywords",
                "handle_inspect_product_image",
                "handle_update_product_listing",
                "handle_update_product_price",
                "handle_upload_product_image",
                "initial_run_state",
                "iso_utc_timestamp",
                "load_scenario",
                "log_abuse_limit_exceeded",
                "main",
                "measurable_write_tool_names",
                "normalize_inspection",
                "numeric_value",
                "production_version",
                "prompt_sha256",
                "prompt_version",
                "publish_event_best_effort",
                "register_product_read_tools",
                "register_product_write_tools",
                "register_terminal_tools",
                "required_steps_completed",
                "resolve_llm_config",
                "run_events_channel",
                "running_seconds_column_value",
                "seed_replay_run",
                "set_agent_abuse_limit_gate",
                "sse_max_concurrent_streams",
                "sse_retry_after_seconds",
                "status_for",
                "to_json_safe",
                "validate_playbook_tools",
            ),
        ),
    },
    "backend/services/aggregates": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "AnalyticsPerformanceInterval",
                "AnalyticsPerformanceRepo",
                "InventoryRepo",
                "MID_LARGE_SHOP",
                "NEW_SHOP",
                "OrderItemsRepo",
                "OrdersRepo",
                "ProductsRepo",
                "ReturnsRepo",
                "Shop",
                "TikTokSyncStateRepo",
                "analytics_performance_intervals",
                "conversion_rate",
                "null",
                "shop_profile",
                "tiktok_sync_state",
                "unavailable",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AnalyticsKpiRollup",
                "GMV_METRICS_MIN_COUNT",
                "HealthDataSource",
                "HealthSnapshot",
                "ProbationStatus",
                "ProxyHealthSignals",
                "ROLLING_WINDOW_DAYS",
                "SHOP_AGE_MID_LARGE_MIN_DAYS",
                "ShopProfile",
                "ShopProfileSignals",
                "compute_after_sales_handling_time_hours",
                "compute_analytics_weighted_product_ctr",
                "compute_conversion_rate_by_category",
                "compute_csat_proxy",
                "compute_dsi_days",
                "compute_fulfillment_accuracy_rate",
                "compute_inventory_turnover",
                "compute_orders_at_sla_risk",
                "compute_promotion_efficiency_denominators",
                "compute_repeat_purchase_rate",
                "compute_seller_fault_cancellation_rate",
                "compute_shop_traffic_conversion_rate",
                "compute_stockout_rate",
            ),
        ),
    },
    "backend/services/alerts": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "SendFn",
                "ZALO_OA_MESSAGE_URL",
                "build_alert_copy",
                "cooldown_seconds",
                "parse_threshold",
                "rule_matches",
            ),
        ),
    },
    "backend/services/analytics_backfill": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "ANALYTICS_BACKFILL_CONCURRENCY_LIMIT",
                "AnalyticsBackfillPartitionsRepo",
                "AsyncSession",
                "RateLimiter",
                "attempts",
                "budget_lock",
                "catalog",
                "catalog_point_in_time",
                "complete",
                "concurrency_limit",
                "coverage_pct",
                "failed",
                "failures",
                "finish",
                "is_complete",
                "mark_complete",
                "mark_failed",
                "rate_limited",
                "record_attempt",
                "record_failure",
                "record_rate_limited",
                "session_lock",
                "should_stop",
                "skipped",
                "stopped_reason",
                "successes",
                "upsert",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ACTIVE_PRODUCT_STATUSES",
                "ALLOWED_BUCKETS",
                "AnalyticsResourceProtocol",
                "BACKFILL_WINDOW_START",
                "BUCKET",
                "BucketCoverageResult",
                "CATALOG_BUCKET",
                "CatalogCountStrategy",
                "CatalogCounts",
                "CatalogPartitionResult",
                "DEFAULT_AUTO_TOPUP_CONCURRENCY_LIMIT",
                "DEFAULT_BUCKET_ORDER",
                "FORBIDDEN_BUCKETS",
                "LIVE_BUCKET",
                "LiveAnalyticsResource",
                "LivePartitionResult",
                "OrchestratorResult",
                "PRODUCT_BUCKET",
                "PRODUCT_COVERAGE_THRESHOLD",
                "PartitionFailureHook",
                "PartitionRunner",
                "PartitionStatus",
                "ProductPartitionResult",
                "ProductPerformanceResource",
                "ProductsSearch",
                "REVENUE_LIVE_COVERAGE_THRESHOLD",
                "RevenuePartitionStatus",
                "StoppedReason",
                "TRAILING_NEW_DAYS",
                "assert_no_forbidden_live_backfill_paths",
                "backfill_live_allowed_get_paths",
                "backfill_main",
                "build_coverage_parser",
                "build_live_shop_rollup_kwargs",
                "build_parser",
                "compute_catalog_counts",
                "compute_live_hours",
                "compute_live_sessions_count",
                "coverage_main",
                "coverage_ratio",
                "coverage_report_to_dict",
                "derive_aov",
                "is_retryable_partition_error",
                "iter_calendar_days",
                "main",
                "persist_partition_failure",
                "sum_live_impressions",
                "sum_live_views",
            ),
        ),
    },
    "backend/services/etl": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "__all__",
                "make_etl_handoff",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ANALYTICS_CHANNELS",
                "DLQ_TOPIC",
                "DlqHandoffFn",
                "LATENCY_BUDGET_SECONDS",
                "RAW_TOPICS",
                "SilverAnalyticsPromoter",
                "SilverOrdersReturnsPromoter",
                "TARGETED_FETCH_INGEST_SOURCE",
                "TransformError",
                "append_targeted_ctor_payload",
                "append_targeted_live_hours_payload",
                "bronze_order_to_upsert_kwargs",
                "bronze_return_to_upsert_kwargs",
                "extract_event_id",
            ),
        ),
    },
    "backend/services/execution": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "error",
                "error_category",
                "idempotency_key",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ANIMATED_CAPABLE_FORMATS",
                "AsyncToolHandler",
                "ExecutionErrorCategory",
                "ExecutionStatus",
                "MAX_DECODED_SIZE_BYTES",
                "MAX_ENCODED_SIZE_BYTES",
                "MAX_IMAGE_PIXELS",
                "NOOP_TOOL_NAMES",
                "PreconditionFailure",
                "PreconditionName",
                "SUPPORTED_DOCUMENT_SIGNATURES",
                "SUPPORTED_IMAGE_SIGNATURES",
                "TaskDispatcher",
                "ToolHandler",
                "ToolRouteEntry",
                "WORKFLOW_TOOL_CATALOG",
                "WorkflowOutcomeRecorder",
                "classify_execution_error",
                "clear_excess_inventory_handler",
                "create_activity_handler",
                "create_hero_product_handler",
                "create_queued_execution",
                "delete_activity_handler",
                "get_rls_boot_check_state",
                "is_tool_registered",
                "mark_execution_finished",
                "optimize_product_handler",
                "record_rls_boot_check_passed",
                "register_async_tool",
                "replenish_inventory_handler",
                "resolve_write_capability",
                "run_approved_tool",
                "run_clear_excess_inventory_chain",
                "run_create_activity_chain",
                "run_create_hero_product_chain",
                "run_delete_activity_chain",
                "run_optimize_product_chain",
                "run_replenish_inventory_chain",
                "run_tool_async",
                "run_update_activity_chain",
                "screen_and_reencode_image",
                "screen_upload_file",
                "update_activity_handler",
            ),
        ),
    },
    "backend/services/feedback": {
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=("OutcomeIngestResult",),
        ),
    },
    "backend/services/ingestion": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "EtlConsumer",
                "create_app",
            ),
        ),
    },
    "backend/services/scoring": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "build_feature_aggregates",
                "clear_excess_4",
                "copy_source",
                "create_activity_7a",
                "create_hero_product_1",
                "delete_activity_7b",
                "expected_impact",
                "health_check_results",
                "next_steps",
                "one_line",
                "optimize_product_2",
                "prevent_cancellation_8a",
                "prevent_refund_8c",
                "prevent_return_8b",
                "process_order_5",
                "replenish_inventory_3",
                "rules_proxy",
                "source_kpi_ids",
                "unavailable",
                "update_activity_7c",
                "why",
                "workflow_key",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "AFTER_SALES_HANDLING_RISK_HOURS",
                "COPY_SOURCE_RULES",
                "CSAT_RISK_THRESHOLD",
                "CTR_HEALTHY_THRESHOLD",
                "CTR_RISK_THRESHOLD",
                "CopySource",
                "DAILY_SCORING_UTC_MINUTE",
                "DEFAULT_AHR_THRESHOLD",
                "DEFAULT_SPS_THRESHOLD",
                "DSI_RISK_DAYS_THRESHOLD",
                "ExecutionWorkflowKey",
                "FULFILLMENT_ACCURACY_RISK_THRESHOLD",
                "INVENTORY_TURNOVER_RISK_THRESHOLD",
                "ImpactConfidence",
                "KPI_DOMAIN",
                "KPI_WORKFLOW_KEYS",
                "KpiId",
                "LifecycleForShopFn",
                "RETURN_RATE_RISK_THRESHOLD",
                "SELLER_FAULT_CANCEL_RISK_THRESHOLD",
                "STOCKOUT_RATE_RISK_THRESHOLD",
                "Severity",
                "SignalType",
                "TechniqueId",
                "VISUAL_LAYER_KPI_IDS",
                "VisualLayerDomain",
                "WORKFLOW_DISPLAY_NAMES",
                "WorkflowExpectedImpact",
                "WorkflowReasoningSummary",
                "WorkflowRecommendation",
                "get_workflows_for_profile",
            ),
        ),
    },
    "backend/services/tiktok": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=("__all__",),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "ACCOUNT_HOLDER_CAPABILITY",
                "ACCOUNT_HOLDER_SHOP_NAME",
                "APP_REVIEW_USER_PHONE",
                "BUSINESS_ADVERTISER_CAPABILITY",
                "BUSINESS_PLACEHOLDER_PHONE",
                "BUSINESS_PLACEHOLDER_SHOP_NAME",
                "COALESCE_68_SECONDS",
                "CatalogEntry",
                "CredentialBindingError",
                "DEFAULT_TIKTOK_AUTH_BASE_URL",
                "DEFAULT_TIKTOK_BASE_URL",
                "DEFERRED_EVENT_PREFIXES",
                "DatabaseRawWebhookEventRecorder",
                "DatabaseWebhookSideEffects",
                "EventHandler",
                "GOVERNED_CAPABILITIES",
                "INVENTORY_CHANGED_CATALOG_ID",
                "MATERIAL_CATALOG_IDS",
                "NoopWebhookSideEffects",
                "PARSE_VERSION",
                "RAW_BODY_MAX_BYTES",
                "REDACTED_VALUE",
                "RawWebhookEventRecorder",
                "TRUNCATION_SUFFIX",
                "TikTokBusinessAdvertiserOAuthCallbackResult",
                "TikTokBusinessAdvertiserOAuthService",
                "TikTokOAuthCallbackParams",
                "TikTokVerifyConnectionService",
                "TikTokWebhookPayload",
                "WEBHOOK_LOG_PATH",
                "WebhookProcessResult",
                "WebhookSideEffects",
                "account_holder_merchant_id",
                "app_review_user_id",
                "build_partner_oauth_facade",
                "catalog_id_for_event",
                "ingest_channel_for_event",
                "is_deferred_webhook_type",
                "is_material_catalog_id",
                "persist_account_holder_tokens",
                "persist_advertiser_oauth_tokens",
                "persist_oauth_tokens",
                "redact_webhook_body",
                "resolve_authorized_shop",
                "tiktok_debug_enabled",
                "verify_capability_binding",
            ),
        ),
    },
    "backend/services/webhook": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "EVENT_CATEGORY_ROUTES",
                "HandoffFn",
                "__all__",
                "raw_event_recorder",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CeleryMaterialAnalyticsDispatcher",
                "ComputeHook",
                "InMemoryMaterialEnqueueGate",
                "MUTEX_TTL_SECONDS",
                "MaterialAnalyticsDispatcher",
                "MaterialEnqueueGate",
                "RedisMaterialEnqueueGate",
                "SessionFactory",
                "app",
                "get_material_analytics_dispatcher",
                "get_material_enqueue_gate",
                "health",
                "lifespan",
                "make_material_etl_handoff",
                "material_compute_env_ready",
                "maybe_enqueue_material_analytics_compute",
                "run_material_analytics_compute",
                "set_material_analytics_dispatcher",
                "set_material_enqueue_gate",
            ),
        ),
    },
    "backend/workers/services/polling": {
        "orphan": AllowedDrift(
            reason=ORPHAN_REASON,
            symbols=(
                "HandoffFn",
                "PermissionDeniedError",
                "ProductionReadClientFactory",
                "RateLimiter",
                "TikTokAPIError",
                "TikTokOAuthService",
                "TikTokSyncStateRepo",
                "end_date_lt",
                "inventory_last_sync_at",
                "make_etl_handoff",
                "rate_limited",
                "refresh_merchant_tokens",
                "resolve_production_read_credential",
                "start_date_ge",
                "sync_livestreams",
                "sync_settlements",
                "sync_state",
                "tiktok_sync_state",
                "time_until_reset",
            ),
        ),
        "undocumented": AllowedDrift(
            reason=UNDOCUMENTED_REASON,
            symbols=(
                "CreateResourcesFn",
                "SleepFn",
                "SyncWorkerFn",
                "check_sandbox_write_catalog_identity_mismatch",
                "mismatch_logger",
                "sync_products_with_local_upsert",
                "sync_sandbox_write_products",
            ),
        ),
    },
}


def module_symbols(module_path: str) -> tuple[set[str], set[str]]:
    """(documented, actual) public symbols for a module path from the map."""
    module_md = backend_module_root(module_path) / "MODULE.md"
    return parse_module_md_public_symbols(module_md), module_public_symbols_from_code(module_path)


def _allowed(module_path: str, kind: str) -> set[str]:
    entry = KNOWN_DRIFT_ALLOWLIST.get(module_path, {}).get(kind)
    return set(entry.symbols) if entry else set()


def run_check(issue: int) -> tuple[bool, str, dict[str, Any]]:  # noqa: ARG001
    modules = parse_architecture_map()
    try:
        changed = git_changed_files()
    except ChangedFilesUnresolved as exc:
        # Never a silent pass: an unresolvable diff is reported with its cause,
        # the same way harness_bootstrap_pin.py degrades (#1540, #1571).
        return (
            False,
            f"Changed-file set unresolved: {exc.reason}",
            {
                "drift": [],
                "missingInterfaces": [],
                "touchedModules": [],
                "allowlisted": [],
                "changedFilesUnresolved": exc.reason,
            },
        )
    touched: set[str] = set()
    for path in changed:
        mod = module_for_file(path, modules)
        if mod:
            touched.add(mod)
    drift: list[dict] = []
    allowlisted: list[str] = []
    for module_path in sorted(touched):
        info = modules.get(module_path)
        if not info or info.tier >= 3:
            continue
        module_md = backend_module_root(module_path) / "MODULE.md"
        if not module_md.exists():
            drift.append({"module": module_path, "error": "MODULE.md missing"})
            continue
        documented, actual = module_symbols(module_path)
        excused_missing = _allowed(module_path, "undocumented")
        excused_orphan = _allowed(module_path, "orphan")
        missing = sorted((actual - documented) - excused_missing)
        orphans = sorted((documented - actual) - excused_orphan)
        allowlisted.extend(
            f"{module_path}:undocumented:{s}"
            for s in sorted((actual - documented) & excused_missing)
        )
        allowlisted.extend(
            f"{module_path}:orphan:{s}" for s in sorted((documented - actual) & excused_orphan)
        )
        if missing or orphans:
            drift.append(
                {
                    "module": module_path,
                    "missingInModuleMd": missing,
                    "orphanInModuleMd": orphans,
                }
            )

    details = {
        "drift": drift,
        "missingInterfaces": [d.get("missingInModuleMd", []) for d in drift],
        "touchedModules": sorted(touched),
        "allowlisted": allowlisted,
    }
    if drift:
        return False, "MODULE.md drift detected", details
    return True, "MODULE.md in sync for touched modules", details


def main() -> int:
    args = parse_args("Validate MODULE.md drift")
    issue = resolve_issue_number(args.issue)
    if issue is None:
        print("error: issue number required", file=sys.stderr)
        return 1
    passed, _, details = run_check(issue)
    detail = ""
    if details.get("changedFilesUnresolved"):
        detail = f"changed-file set unresolved: {details['changedFilesUnresolved']}"
    elif details.get("drift"):
        detail = f"{len(details['drift'])} module(s) out of sync"
    else:
        detail = (
            f"{len(details['touchedModules'])} module(s) checked, "
            f"{len(details['allowlisted'])} allowlisted symbol(s)"
        )
    return print_check_result("module_md_sync", passed, detail)


if __name__ == "__main__":
    raise SystemExit(main())
