"use client";

import sampleRankings from "../../lib/shop-analysis/sample-rankings.json";
import type { QueryState } from "../../lib/phan-tich/model";
import type { RankedMetric, RankedStream, RankingEnvelope, RankingLoader } from "../../lib/phan-tich/types";
import type { ShopAnalysisEnvelope } from "../../lib/shop-analysis/types";
import { PhanTichView } from "./phan-tich-view";

/**
 * The anonymous Phân tích (AC-8.6): the bundled synthetic sample report (an
 * invented shop, held by the shell's `useShopReport`) and its sample rankings,
 * both generated by `scripts/demo_analysis_sample.py` through the real
 * backend builders over synthetic data — never a real shop. Bundled
 * statically: viewing it issues no request (an entry of
 * `replay-module-graph.test.ts`).
 */
const FIXTURE = sampleRankings as unknown as Partial<
  Record<RankedStream, Partial<Record<RankedMetric, RankingEnvelope>>>
>;

export const loadSampleRanking: RankingLoader = async (stream, metric) => FIXTURE[stream]?.[metric] ?? null;

export function SamplePhanTich({
  envelope,
  query,
  onNavigate,
}: {
  readonly envelope: ShopAnalysisEnvelope;
  readonly query: QueryState;
  readonly onNavigate?: (href: string) => void;
}) {
  return <PhanTichView envelope={envelope} loadRanking={loadSampleRanking} onNavigate={onNavigate} query={query} sample />;
}
