"""Shared golden-shaped fixture builders for the ADR-077 §6 gate suite
(#1045, W2-B phase gate).

**Fixture provenance — read before reusing.** No genuinely captured
multi-day ``analytics_performance_intervals`` time series was obtainable for
this slice: this worktree deliberately carries no ``.env``/``DATABASE_URL``
(the primary checkout's remote pooler is explicitly off-limits to executor
worktrees), and even with credentials, querying the live reference-shop
database to mint a *new* fixture is exactly the kind of remote-DB touch this
worktree must not perform. Every daily series built here is **synthetic**,
generated by the pure, deterministic :func:`daily_value` / :func:`daily_rate_value`
/ :func:`daily_int_value` below from one injected ``REFERENCE_DATE`` anchor —
never ``date.today()``/``datetime.now()`` for anything that participates in
elapsed-time logic (the #1032 lesson: a frozen calendar date compared against
real wall-clock time ages out overnight and turns a passing suite red with no
code change).

The honest anchors to real data: per-day magnitudes are scaled off
``tests/fixtures/analytics_backfill/product/a34_page1.json``, a genuinely
captured TikTok Partner "Product Performance" API response already checked
into this repo for the analytics-backfill slice (not authored here). That
fixture is a single aggregate snapshot, not a daily series, so it can only
anchor *magnitude* per metric family:

- revenue/orders: ``gmv / orders`` -> :func:`anchor_gmv_per_order`.
- impressions/CTR: the snapshot's own ``ctr`` field (``0.0759``) ->
  :func:`anchor_ctr`. The snapshot carries no daily *impressions* count at
  all (only the derived ``ctr`` ratio), so :func:`impressions_base_for`
  falls back to a plausible flat magnitude (documented there, not silently
  invented) rather than claiming a captured anchor that does not exist.
- conversion: the snapshot has no ``conversion_rate`` field either, but
  does carry ``click_order_rate`` (``0.1064``) — order-to-click conversion,
  the closest captured proxy for the shape this package calls
  ``conversion_rate`` — used honestly labelled as a proxy, never presented
  as the same field, via :func:`anchor_conversion_rate_proxy`.

This mirrors the W1 precedent at
``tests/fixtures/agent_sanitize_golden/synthetic/``: synthetic data, shipped
clearly labelled as synthetic, anchored to real observed scale wherever
possible — never hand-authored numbers described as "captured".

**The weekly-seasonality trick.** ``_WEEKDAY_PATTERN`` is a 7-value
multiplier cycle that sums to exactly ``7.00`` (mean ``1.00``). Every window
the compute path reads (pre: 14 days: 2 full cycles; preliminary post: 7
days: 1 full cycle; final post: 14 days: 2 full cycles) is phase-invariant
over this cycle, so its mean multiplier is exactly ``1.00`` regardless of
which calendar day the window starts on. That makes each fixture's
*expected* pre/post mean exactly its ``base`` value (mod rounding), and
because it is genuine day-to-day variation (not a constant series), Pearson
correlation between an affine-scaled sibling and the target is a real,
non-degenerate ``~1.0`` — never the constant-series ``0.0`` degenerate case
that silently collapses a "non-fallback" test onto the fallback branch (see
each gate file's own note on asserting ``used_fallback is False``).
"""

from __future__ import annotations

import json
import uuid
from datetime import UTC, date, datetime, time, timedelta
from decimal import Decimal
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from juli_backend.models.models import (
    AnalyticsPerformanceInterval,
    ImpactReading,
    Product,
    Shop,
    ToolExecution,
    User,
)

#: The single injected "now" every date in the gate suite derives from.
REFERENCE_DATE = date(2026, 4, 1)

#: A genuinely captured reference-shop API snapshot, checked into this repo
#: by the analytics-backfill slice — see the module docstring.
_CAPTURED_ANCHOR_PATH = (
    Path(__file__).resolve().parents[1]
    / "fixtures"
    / "analytics_backfill"
    / "product"
    / "a34_page1.json"
)

_WEEKDAY_PATTERN: tuple[Decimal, ...] = (
    Decimal("1.00"),
    Decimal("1.05"),
    Decimal("0.95"),
    Decimal("1.10"),
    Decimal("0.90"),
    Decimal("1.15"),
    Decimal("0.85"),
)
assert sum(_WEEKDAY_PATTERN, start=Decimal(0)) == Decimal("7.00")


def _pattern_multiplier(day: date) -> Decimal:
    return _WEEKDAY_PATTERN[day.toordinal() % 7]


def daily_value(day: date, base: Decimal, shock: Decimal = Decimal(1)) -> Decimal:
    """One money-scale day's value (2dp): ``base`` x weekday-seasonality x an
    optional shock multiplier (identity by default)."""
    return (base * _pattern_multiplier(day) * shock).quantize(Decimal("0.01"))


def daily_rate_value(day: date, base: Decimal, shock: Decimal = Decimal(1)) -> Decimal:
    """One rate-scale (``ctr``/``conversion_rate``, ``Numeric(10, 6)``) day's
    value: same weekday-seasonality x shock construction as
    :func:`daily_value`, quantized to 6dp instead of 2dp."""
    return (base * _pattern_multiplier(day) * shock).quantize(Decimal("0.000001"))


def daily_int_value(day: date, base: int | Decimal, shock: Decimal = Decimal(1)) -> int:
    """One integer-column (``impressions``/``visitors``/``sku_orders``) day's
    value: same weekday-seasonality x shock construction, rounded to the
    nearest whole event count."""
    return int((Decimal(base) * _pattern_multiplier(day) * shock).quantize(Decimal("1")))


def anchor_gmv_per_order() -> Decimal:
    """The real number the revenue/orders family scales from: ``gmv /
    orders`` from the genuinely captured reference-shop snapshot."""
    payload = json.loads(_CAPTURED_ANCHOR_PATH.read_text())
    perf = payload["products"][0]["total_performance"]
    gmv = Decimal(perf["gmv"]["amount"])
    orders = Decimal(perf["orders"])
    return (gmv / orders).quantize(Decimal("0.01"))


def anchor_ctr() -> Decimal:
    """The real number the impressions/CTR family's *rate* scales from: the
    captured snapshot's own ``ctr`` field."""
    payload = json.loads(_CAPTURED_ANCHOR_PATH.read_text())
    return Decimal(payload["products"][0]["total_performance"]["ctr"])


def anchor_conversion_rate_proxy() -> Decimal:
    """The real number the conversion family's rate scales from.

    The captured snapshot has no ``conversion_rate`` field (this package's
    ``conversion_rate`` is a distinct Partner-API metric from what the
    snapshot exposes); its closest captured proxy is ``click_order_rate``
    (order-to-click conversion) — used here honestly as a *proxy* anchor for
    the right order of magnitude, never presented as a captured
    ``conversion_rate`` value itself.
    """
    payload = json.loads(_CAPTURED_ANCHOR_PATH.read_text())
    return Decimal(payload["products"][0]["total_performance"]["click_order_rate"])


def impressions_base_default() -> Decimal:
    """The impressions/CTR family's *volume* baseline (the raw ``impressions``
    column, distinct from the ``ctr`` rate itself which IS captured — see
    :func:`anchor_ctr`).

    No daily impressions count exists in the captured anchor snapshot at all
    (only the derived ``ctr`` ratio) — this is a documented, deliberate
    plausibility construction, not a second captured anchor: a round figure
    comfortably above ``>= 50/day`` (the ADR-077 decision 4 floor), in fact
    ``>= 3x`` it, so `Cao`-eligible fixtures (which additionally require
    ``>= 3x floor``) are reachable without every test having to hand-pick a
    magnitude.
    """
    return Decimal(900)


def anchor_dt(d: date = REFERENCE_DATE) -> datetime:
    return datetime.combine(d, time.min, tzinfo=UTC)


async def make_shop(session: AsyncSession, *, phone_suffix: str, name: str) -> Shop:
    phone = f"+849{phone_suffix}"
    assert len(phone) <= 20, f"User.phone is String(20); {phone!r} is too long"
    user = User(id=uuid.uuid4(), phone=phone)
    shop = Shop(
        id=uuid.uuid4(),
        user_id=user.id,
        shop_name=name,
        tiktok_shop_id=f"tts_{phone_suffix}",
    )
    session.add_all([user, shop])
    await session.flush()
    return shop


async def make_product(
    session: AsyncSession, shop: Shop, tiktok_product_id: str, *, created: date
) -> Product:
    product = Product(
        id=uuid.uuid4(),
        shop_id=shop.id,
        tiktok_product_id=tiktok_product_id,
        name=f"Product {tiktok_product_id}",
        status="active",
        tiktok_created_at=anchor_dt(created),
        update_time=anchor_dt(),
    )
    session.add(product)
    await session.flush()
    return product


async def make_execution(
    session: AsyncSession,
    shop: Shop,
    *,
    tiktok_product_id: str,
    t: date,
    approval_suffix: str,
    price_update: bool = True,
    description: str | None = None,
    title: str | None = None,
    image: bool = False,
) -> ToolExecution:
    """A ``listing.optimize_product`` execution. Exactly which
    ``MutationKind``(s) get classified (and therefore which metric family
    the reading lands on) is controlled by which of ``price_update``/
    ``description``/``title``/``image`` the caller sets — mirroring
    ``classify.classify_mutation_kinds``'s own field reads, so a caller can
    build a SEO-only, description-only, or image-only run to drive
    ``impressions``/``conversion_rate``/``ctr`` readings specifically,
    rather than always defaulting to the price mutation's ``gmv``.
    """
    payload: dict[str, object] = {
        "product_id": tiktok_product_id,
        "workflow_id": "optimize_product_2",
    }
    if price_update:
        payload["price_update"] = {"price": "19.99"}
    if image:
        payload["image_uri"] = f"https://cdn.example/{tiktok_product_id}/hero.jpg"
    edit_body: dict[str, str] = {}
    if title is not None:
        edit_body["title"] = title
    if description is not None:
        edit_body["description"] = description
    if edit_body:
        payload["edit_body"] = edit_body
    execution = ToolExecution(
        id=uuid.uuid4(),
        shop_id=shop.id,
        approval_id=f"approval-1045-{approval_suffix}",
        tool_name="listing.optimize_product",
        payload_json=json.dumps(payload),
        status="succeeded",
        updated_at=anchor_dt(t),
    )
    session.add(execution)
    await session.flush()
    return execution


async def add_daily_rows(
    session: AsyncSession,
    shop: Shop,
    tiktok_product_id: str,
    start: date,
    end: date,
    *,
    gmv_base: Decimal | None = None,
    gmv_constant: Decimal | None = None,
    shock_from: date | None = None,
    shock: Decimal = Decimal(1),
    sku_orders_per_day: int = 8,
    impressions_per_day: int = 600,
    impressions_base: int | Decimal | None = None,
    ctr: Decimal = Decimal("0.06"),
    ctr_base: Decimal | None = None,
    conversion_rate: Decimal | dict[date, Decimal] | None = None,
    conversion_rate_base: Decimal | None = None,
    visitors_per_day: int = 120,
    items_sold_per_day: int | None = None,
) -> None:
    """Write one product's daily ``AnalyticsPerformanceInterval`` rows over
    ``[start, end]``.

    Every column defaults to a flat, real-shaped constant unless a
    "``_base``"/"``_constant``" variant is given, in which case that column
    is generated through the shared weekday-pattern + ``shock`` construction
    (:func:`daily_value` for ``gmv``, :func:`daily_int_value` for
    ``impressions``, :func:`daily_rate_value` for ``ctr``/
    ``conversion_rate``) — the same ``shock_from``/``shock`` pair applies to
    whichever ``_base`` column(s) the caller supplies, so a single fixture
    can shock more than one metric family at once (the shock-cancellation
    gate's shop-wide-shock scenarios need exactly this). ``gmv_constant`` is
    a flat, zero-variance override used only by the low-correlation
    suppression fixture; it and ``gmv_base`` are mutually exclusive.
    """
    current = start
    while current <= end:
        active_shock = shock if (shock_from is None or current >= shock_from) else Decimal(1)

        if gmv_constant is not None:
            gmv = gmv_constant
        elif gmv_base is not None:
            gmv = daily_value(current, gmv_base, active_shock)
        else:
            gmv = None

        impressions = (
            daily_int_value(current, impressions_base, active_shock)
            if impressions_base is not None
            else impressions_per_day
        )
        ctr_value = (
            daily_rate_value(current, ctr_base, active_shock) if ctr_base is not None else ctr
        )

        if isinstance(conversion_rate, dict):
            conv = conversion_rate.get(current)
        elif conversion_rate_base is not None:
            conv = daily_rate_value(current, conversion_rate_base, active_shock)
        else:
            conv = conversion_rate

        row = AnalyticsPerformanceInterval(
            id=uuid.uuid4(),
            shop_id=shop.id,
            snapshot_key=f"impact-gate/{tiktok_product_id}/{current.isoformat()}",
            grain="product",
            start_date=current,
            tiktok_product_id=tiktok_product_id,
            gmv=gmv,
            sku_orders=sku_orders_per_day,
            items_sold=(
                items_sold_per_day if items_sold_per_day is not None else sku_orders_per_day
            ),
            impressions=impressions,
            ctr=ctr_value,
            conversion_rate=conv,
            visitors=visitors_per_day,
            update_time=anchor_dt(current),
        )
        session.add(row)
        current += timedelta(days=1)
    await session.flush()


#: Which ``add_daily_rows`` keyword the requested control-sibling ``family``
#: is scaled into — the single dispatch table :func:`add_control_siblings`
#: reads, so adding a new correlated-family fixture is a one-line addition
#: here rather than a new branch in every caller.
_FAMILY_BASE_KWARG: dict[str, str] = {
    "gmv": "gmv_base",
    "impressions": "impressions_base",
    "ctr": "ctr_base",
    "conversion_rate": "conversion_rate_base",
}


async def add_control_siblings(
    session: AsyncSession,
    shop: Shop,
    *,
    scales: list[Decimal],
    base: Decimal,
    start: date,
    end: date,
    name_prefix: str,
    created: date,
    family: str = "gmv",
    shock_from: date | None = None,
    shock: Decimal = Decimal(1),
    **extra_daily_kwargs: object,
) -> list[str]:
    """Create ``len(scales)`` same-shop sibling products, each tracking the
    target's own weekday pattern — for whichever metric ``family`` names —
    at a different scale: an affine transform of the same shape, so Pearson
    correlation against the target is exactly ``1.0`` (correlation is
    invariant under a positive affine rescale). None of them carry a
    ``ToolExecution``, so they are never "touched" by construction.

    ``extra_daily_kwargs`` passes through to :func:`add_daily_rows`
    unchanged (e.g. a caller building ``ctr``-family siblings can still set
    ``visitors_per_day``/``sku_orders_per_day`` so every OTHER metric's
    volume floor stays comfortably clear too, independent of which single
    column is being correlated).
    """
    base_kwarg = _FAMILY_BASE_KWARG[family]
    ids: list[str] = []
    for i, scale in enumerate(scales):
        product_id = f"{name_prefix}-{i}"
        await make_product(session, shop, product_id, created=created)
        await add_daily_rows(
            session,
            shop,
            product_id,
            start,
            end,
            shock_from=shock_from,
            shock=shock,
            **{base_kwarg: base * scale},
            **extra_daily_kwargs,
        )
        ids.append(product_id)
    return ids


async def readings_for(session: AsyncSession, execution_id: uuid.UUID) -> list[ImpactReading]:
    stmt = select(ImpactReading).where(ImpactReading.tool_execution_id == execution_id)
    result = await session.execute(stmt)
    return list(result.scalars().all())
