"""Shared golden-shaped fixture builders for the ADR-077 §6 gate suite
(#1045, W2-B phase gate).

**Fixture provenance — read before reusing.** No genuinely captured
multi-day ``analytics_performance_intervals`` time series was obtainable for
this slice: this worktree deliberately carries no ``.env``/``DATABASE_URL``
(the primary checkout's remote pooler is explicitly off-limits to executor
worktrees), and even with credentials, querying the live reference-shop
database to mint a *new* fixture is exactly the kind of remote-DB touch this
worktree must not perform. Every daily series built here is **synthetic**,
generated by the pure, deterministic :func:`daily_value` below from one
injected ``REFERENCE_DATE`` anchor — never ``date.today()``/
``datetime.now()`` for anything that participates in elapsed-time logic (the
#1032 lesson: a frozen calendar date compared against real wall-clock time
ages out overnight and turns a passing suite red with no code change).

The one honest anchor to real data: per-day magnitudes are scaled off
``tests/fixtures/analytics_backfill/product/a34_page1.json``, a genuinely
captured TikTok Partner "Product Performance" API response already checked
into this repo for the analytics-backfill slice (not authored here). That
fixture is a single aggregate snapshot, not a daily series, so it can only
anchor *magnitude* (a real observed per-order GMV figure), never be
replayed directly as a multi-day series. This mirrors the W1 precedent at
``tests/fixtures/agent_sanitize_golden/synthetic/``: synthetic data, shipped
clearly labelled as synthetic, anchored to real observed scale wherever
possible — never hand-authored numbers described as "captured".

**The weekly-seasonality trick.** ``_WEEKDAY_PATTERN`` is a 7-value
multiplier cycle that sums to exactly ``7.00`` (mean ``1.00``). Every window
the compute path reads (pre: 14 days: 2 full cycles; preliminary post: 7
days: 1 full cycle; final post: 14 days: 2 full cycles) is phase-invariant
over this cycle, so its mean multiplier is exactly ``1.00`` regardless of
which calendar day the window starts on. That makes each fixture's
*expected* pre/post mean exactly its ``base`` value (mod per-day cent
rounding) — gate-suite assertions compare against an exactly-computable
expected number through this same function, never a hand-typed magic
constant.
"""

from __future__ import annotations

import json
import uuid
from datetime import UTC, date, datetime, time, timedelta
from decimal import Decimal
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from juli_backend.models.models import (
    AnalyticsPerformanceInterval,
    ImpactReading,
    Product,
    Shop,
    ToolExecution,
    User,
)

#: The single injected "now" every date in the gate suite derives from.
REFERENCE_DATE = date(2026, 4, 1)

#: A genuinely captured reference-shop API snapshot, checked into this repo
#: by the analytics-backfill slice — see the module docstring.
_CAPTURED_ANCHOR_PATH = (
    Path(__file__).resolve().parents[1]
    / "fixtures"
    / "analytics_backfill"
    / "product"
    / "a34_page1.json"
)

_WEEKDAY_PATTERN: tuple[Decimal, ...] = (
    Decimal("1.00"),
    Decimal("1.05"),
    Decimal("0.95"),
    Decimal("1.10"),
    Decimal("0.90"),
    Decimal("1.15"),
    Decimal("0.85"),
)
assert sum(_WEEKDAY_PATTERN, start=Decimal(0)) == Decimal("7.00")


def anchor_gmv_per_order() -> Decimal:
    """The one real number every fixture in this suite scales from:
    ``gmv / orders`` from the genuinely captured reference-shop snapshot at
    ``_CAPTURED_ANCHOR_PATH``."""
    payload = json.loads(_CAPTURED_ANCHOR_PATH.read_text())
    perf = payload["products"][0]["total_performance"]
    gmv = Decimal(perf["gmv"]["amount"])
    orders = Decimal(perf["orders"])
    return (gmv / orders).quantize(Decimal("0.01"))


def _pattern_multiplier(day: date) -> Decimal:
    return _WEEKDAY_PATTERN[day.toordinal() % 7]


def daily_value(day: date, base: Decimal, shock: Decimal = Decimal(1)) -> Decimal:
    """One day's value: ``base`` x weekday-seasonality x an optional shock
    multiplier (identity by default). Every fixture computes its raw series
    *and* every test computes its own expected numbers through this same
    function, so assertions never hand-type a derived magnitude."""
    return (base * _pattern_multiplier(day) * shock).quantize(Decimal("0.01"))


def anchor_dt(d: date = REFERENCE_DATE) -> datetime:
    return datetime.combine(d, time.min, tzinfo=UTC)


async def make_shop(session: AsyncSession, *, phone_suffix: str, name: str) -> Shop:
    phone = f"+849{phone_suffix}"
    assert len(phone) <= 20, f"User.phone is String(20); {phone!r} is too long"
    user = User(id=uuid.uuid4(), phone=phone)
    shop = Shop(
        id=uuid.uuid4(),
        user_id=user.id,
        shop_name=name,
        tiktok_shop_id=f"tts_{phone_suffix}",
    )
    session.add_all([user, shop])
    await session.flush()
    return shop


async def make_product(
    session: AsyncSession, shop: Shop, tiktok_product_id: str, *, created: date
) -> Product:
    product = Product(
        id=uuid.uuid4(),
        shop_id=shop.id,
        tiktok_product_id=tiktok_product_id,
        name=f"Product {tiktok_product_id}",
        status="active",
        tiktok_created_at=anchor_dt(created),
        update_time=anchor_dt(),
    )
    session.add(product)
    await session.flush()
    return product


async def make_execution(
    session: AsyncSession,
    shop: Shop,
    *,
    tiktok_product_id: str,
    t: date,
    approval_suffix: str,
    price_update: bool = True,
    description: str | None = None,
) -> ToolExecution:
    payload: dict[str, object] = {
        "product_id": tiktok_product_id,
        "workflow_id": "optimize_product_2",
    }
    if price_update:
        payload["price_update"] = {"price": "19.99"}
    if description is not None:
        payload["edit_body"] = {"description": description}
    execution = ToolExecution(
        id=uuid.uuid4(),
        shop_id=shop.id,
        approval_id=f"approval-1045-{approval_suffix}",
        tool_name="listing.optimize_product",
        payload_json=json.dumps(payload),
        status="succeeded",
        updated_at=anchor_dt(t),
    )
    session.add(execution)
    await session.flush()
    return execution


async def add_daily_rows(
    session: AsyncSession,
    shop: Shop,
    tiktok_product_id: str,
    start: date,
    end: date,
    *,
    gmv_base: Decimal | None = None,
    gmv_constant: Decimal | None = None,
    shock_from: date | None = None,
    shock: Decimal = Decimal(1),
    sku_orders_per_day: int = 8,
    impressions_per_day: int = 600,
    ctr: Decimal = Decimal("0.06"),
    conversion_rate: Decimal | dict[date, Decimal] | None = None,
    visitors_per_day: int = 120,
    items_sold_per_day: int | None = None,
) -> None:
    """Write one product's daily ``AnalyticsPerformanceInterval`` rows over
    ``[start, end]``.

    ``gmv_base`` (weekday-patterned via :func:`daily_value`, with ``shock``
    applied only from ``shock_from`` onward) and ``gmv_constant`` (a flat,
    zero-variance override used only by the low-correlation suppression
    fixture) are mutually exclusive; neither given leaves ``gmv`` ``NULL``.
    Every other column is a flat, real-shaped constant unless overridden —
    no gate-suite assertion depends on their exact daily shape.
    """
    current = start
    while current <= end:
        if gmv_constant is not None:
            gmv = gmv_constant
        elif gmv_base is not None:
            active_shock = shock if (shock_from is None or current >= shock_from) else Decimal(1)
            gmv = daily_value(current, gmv_base, active_shock)
        else:
            gmv = None

        if isinstance(conversion_rate, dict):
            conv = conversion_rate.get(current)
        else:
            conv = conversion_rate

        row = AnalyticsPerformanceInterval(
            id=uuid.uuid4(),
            shop_id=shop.id,
            snapshot_key=f"impact-gate/{tiktok_product_id}/{current.isoformat()}",
            grain="product",
            start_date=current,
            tiktok_product_id=tiktok_product_id,
            gmv=gmv,
            sku_orders=sku_orders_per_day,
            items_sold=(
                items_sold_per_day if items_sold_per_day is not None else sku_orders_per_day
            ),
            impressions=impressions_per_day,
            ctr=ctr,
            conversion_rate=conv,
            visitors=visitors_per_day,
            update_time=anchor_dt(current),
        )
        session.add(row)
        current += timedelta(days=1)
    await session.flush()


async def add_control_siblings(
    session: AsyncSession,
    shop: Shop,
    *,
    scales: list[Decimal],
    gmv_base: Decimal,
    start: date,
    end: date,
    name_prefix: str,
    created: date,
    shock_from: date | None = None,
    shock: Decimal = Decimal(1),
) -> list[str]:
    """Create ``len(scales)`` same-shop sibling products, each tracking the
    target's own weekday pattern at a different scale — an affine transform
    of the same shape, so Pearson correlation against the target is exactly
    ``1.0`` (correlation is invariant under a positive affine rescale). None
    of them carry a ``ToolExecution``, so they are never "touched" by
    construction."""
    ids: list[str] = []
    for i, scale in enumerate(scales):
        product_id = f"{name_prefix}-{i}"
        await make_product(session, shop, product_id, created=created)
        await add_daily_rows(
            session,
            shop,
            product_id,
            start,
            end,
            gmv_base=gmv_base * scale,
            shock_from=shock_from,
            shock=shock,
        )
        ids.append(product_id)
    return ids


async def readings_for(session: AsyncSession, execution_id: uuid.UUID) -> list[ImpactReading]:
    stmt = select(ImpactReading).where(ImpactReading.tool_execution_id == execution_id)
    result = await session.execute(stmt)
    return list(result.scalars().all())
